export const KNOWLEDGE = {
  verbas: {
    name: "Agente de Verbas",
    color: "#7C3AED",
    emoji: "💰",
    subtitle: "Comercial & Trade",
    greeting: "Olá! Sou o Agente de Verbas da Embelleze. Posso te ajudar com tudo sobre verbas comerciais e trade. Como posso ajudar?",
    suggested: ["A ação já foi realizada no cliente?", "Qual é o prazo para cadastrar a verba?", "Quem aprova a verba?", "Como funciona o encontro de contas?"],
    qa: [
      // VENDEDOR — 70 perguntas
      { q: ["ação já foi realizada", "ação origem verba", "verba antes da ação"], a: "A verba deve ser cadastrada após a ação realizada no cliente." },
      { q: ["cadastro dentro do prazo", "prazo para cadastrar"], a: "O representante tem até 30 dias após ocorrer a ação para cadastrar a verba." },
      { q: ["cadastro no mercanet", "onde cadastra verba", "sistema verba"], a: "Sim. O processo de cadastro de verbas ocorre no Mercanet." },
      { q: ["caminho mercanet verba", "menu mercanet", "ações de verbas caminho"], a: "Para cadastro de verba, o caminho é: Menu – Ações de Verbas – Ações de Verbas." },
      { q: ["clicar novo", "botão novo verba", "iniciar cadastro"], a: "O cadastro deve ser iniciado pela opção 'Novo', no canto superior esquerdo da janela." },
      { q: ["código do cliente", "informar código cliente", "campo cliente"], a: "O representante deve informar o código do cliente desejado." },
      { q: ["busca lupa cliente", "lupa código cliente", "não sabe código"], a: "Quando não souber o código, deve-se clicar na lupa ao lado do campo código do cliente para realizar a busca." },
      { q: ["empresa que atende cliente", "selecionar empresa", "qual empresa"], a: "Deve ser selecionada a empresa pela qual o cliente é atendido." },
      { q: ["razão social preenchida", "campos automáticos", "uf ga gr automático"], a: "Ao selecionar o cliente, os campos Razão Social, UF, GA e GR são preenchidos automaticamente." },
      { q: ["empresa que fatura", "empresa faturamento cliente"], a: "O representante deve selecionar a empresa que fatura para o cliente." },
      { q: ["tipo de verba", "comercial ou trade", "classificação verba"], a: "O tipo de verba deve ser informado como Comercial ou Trade." },
      { q: ["tipo de ação", "ação realizada cliente", "selecionar ação"], a: "O representante deve selecionar qual ação foi realizada no cliente." },
      { q: ["data da ação", "informar data", "mês da ação"], a: "Deve ser selecionado o mês da ação realizada no cliente." },
      { q: ["regra data ação", "limite data ação", "1 mês anterior"], a: "O campo permite somente a seleção de 1 mês anterior à data de lançamento da verba." },
      { q: ["valor do pagamento", "informar valor verba", "campo valor"], a: "Deve ser informado o valor da verba a ser paga." },
      { q: ["forma de pagamento verba", "como verba será paga", "campo forma pagamento"], a: "Deve ser informado como a verba será paga ao cliente." },
      { q: ["anexos verba", "documentos anexar", "incluir anexos"], a: "Toda documentação necessária deve ser anexada para dar andamento à verba." },
      { q: ["documentação completa", "documentação anexada correta"], a: "O processo exige anexar a documentação necessária para análise e aprovação." },
      { q: ["gravar cadastro", "salvar verba", "botão gravar"], a: "Após preencher os campos e anexar documentos, deve-se clicar no botão gravar." },
      { q: ["campos obrigatórios representante", "responsabilidade representante campos"], a: "Empresa, tipo de verba, tipo de ação, data de ação, valor, forma de pagamento e anexos são de responsabilidade do representante." },
      { q: ["workflow aprovação", "verba entrou aprovação", "fluxo aprovação verba"], a: "Após o cadastro, a verba segue para o fluxo de aprovação." },
      { q: ["primeiro aprovador verba", "quem aprova primeiro"], a: "O primeiro aprovador é o Gestor de Área." },
      { q: ["gestor área analisou documentação", "ga analisa documentação"], a: "O Gestor de Área deve analisar a documentação anexada." },
      { q: ["gestor área aprovou reprovou", "ga decisão verba"], a: "O Gestor de Área deve clicar em Aprovar ou Reprovar." },
      { q: ["finalizar atividade ga", "incluir finalizar ga", "ga finalizou atividade"], a: "Depois da decisão, o Gestor de Área deve clicar em Incluir e Finalizar Atividade." },
      { q: ["prazo gestor área", "prazo ga aprovação", "7 dias ga"], a: "O Gestor de Área tem até 7 dias a partir da data de cadastro." },
      { q: ["após gestor área quem aprova", "segundo aprovador", "próximo aprovador ga"], a: "O próximo aprovador é o Gestor Regional." },
      { q: ["gestor regional validou saldo", "gr valida saldo", "saldo gr"], a: "Nessa etapa é feita a validação do saldo para reservar o valor." },
      { q: ["valor reservado gr", "reserva valor verba", "gr reservou valor"], a: "Havendo saldo, o valor é reservado para a verba." },
      { q: ["gr analisou documentação", "gestor regional documentação"], a: "Sim. O Gestor Regional deve analisar a documentação inserida." },
      { q: ["gr aprovou reprovou", "gestor regional decisão"], a: "O Gestor Regional deve clicar em Aprovar ou Reprovar." },
      { q: ["finalizar atividade gr", "gr incluir finalizar"], a: "O Gestor Regional deve clicar em Incluir e Finalizar Atividade." },
      { q: ["prazo gestor regional", "prazo gr aprovação", "7 dias gr"], a: "O Gestor Regional tem até 7 dias a partir da data de cadastro." },
      { q: ["saldo suficiente aprovação", "tem saldo verba", "verificar saldo"], a: "O sistema valida se existe saldo disponível para reservar o valor." },
      { q: ["não há saldo suficiente", "sem saldo o que ocorre", "falta saldo verba"], a: "O gestor consegue aprovar a ocorrência, mas ela segue para dupla aprovação." },
      { q: ["dupla aprovação falta saldo", "quem aprova sem saldo", "gestão nacional saldo"], a: "Gestor Nacional de Vendas e Gestor Financeiro participam da dupla aprovação." },
      { q: ["sistema informa falta saldo", "mensagem sem saldo", "aviso saldo insuficiente"], a: "Sim. É apresentada mensagem informando que não existe saldo e o valor que deve ser acrescido." },
      { q: ["diferença creditada gestão nacional", "crédito diferença aprovação"], a: "Com a aprovação, a diferença dos valores é automaticamente creditada." },
      { q: ["após gestão nacional para onde vai", "fluxo depois gestão nacional"], a: "Segue para aprovação da Administração de Vendas." },
      { q: ["adm vendas validou documentação", "administração vendas verifica"], a: "A Administração de Vendas deve validar as documentações." },
      { q: ["adm vendas pode reprovar", "administração reprova verba"], a: "Sim. Pode reprovar e devolver ao representante para ajustes necessários." },
      { q: ["adm vendas encaminha coordenação", "administração para coordenação"], a: "Sim. Se estiver correta, encaminha para a Coordenação de Vendas." },
      { q: ["prazo administração vendas", "7 dias adm vendas", "prazo adm"], a: "O setor tem até 7 dias a partir da data de cadastro." },
      { q: ["quando gestão nacional é acionada", "gestão nacional quando entra"], a: "Quando não existe crédito suficiente na aprovação do Gestor Regional ou do Gestor de Área, quando não houver regional." },
      { q: ["gestão nacional dupla aprovação", "gn depende dupla aprovação"], a: "Sim. Gestor Nacional de Vendas junto ao Gestor Financeiro." },
      { q: ["prazo gestão nacional", "7 dias gestão nacional", "prazo gn"], a: "A gestão tem até 7 dias a partir da data de cadastro." },
      { q: ["última aprovação verba", "quem faz última aprovação"], a: "A última etapa é a Coordenação de Vendas." },
      { q: ["ok coordenação de vendas", "após aprovação coordenação"], a: "A verba fica aguardando a entrada do próximo pedido." },
      { q: ["quando encontro de contas ocorre", "encontro de contas próximo pedido"], a: "O encontro de contas ocorre com a entrada do próximo pedido." },
      { q: ["quando verba é paga", "pagamento verba quando", "receber verba"], a: "O pagamento ocorre por meio do encontro de contas no próximo pedido." },
      { q: ["valor deixa de ser reservado", "quando reserva encerra"], a: "Na aprovação da Coordenação de Vendas." },
      { q: ["valor debitado conta gestor", "debito definitivo gestor"], a: "Na etapa final, após a aprovação da Coordenação de Vendas." },
      { q: ["prazo coordenação vendas", "7 dias coordenação", "prazo coord"], a: "O setor tem até 7 dias a partir da data de cadastro." },
      { q: ["backoffice lançamento crédito", "backoffice verba", "lançamento manual backoffice"], a: "Sim. Existe processo de Backoffice para lançamento de créditos." },
      { q: ["caminho backoffice lançamento", "menu lançamento manual", "lançamentos manuais conta corrente"], a: "Menu – Ações de Verbas – Lançamentos Manuais em Conta Corrente." },
      { q: ["lançamento manual definitivo", "lançamento manual temporário"], a: "O documento informa que esse tipo de lançamento ficará disponível até liberação do cálculo automático." },
      { q: ["tipo lançamento backoffice", "crédito lançamento tipo"], a: "Deve selecionar o tipo de lançamento 'Crédito'." },
      { q: ["conta investimento backoffice", "comercial ou trade backoffice"], a: "A conta poderá ser Comercial ou Trade." },
      { q: ["quem recebe crédito backoffice", "gestor regional crédito", "código gr lançamento"], a: "Deve ser informado o código do Gestor Regional que receberá o crédito previamente calculado." },
      { q: ["data lançamento crédito", "o que é data lançamento"], a: "É o início da vigência do crédito liberado." },
      { q: ["data vigência crédito", "o que é data vigência"], a: "É a validade do crédito até a data em que poderão ser lançadas verbas e utilizado o valor." },
      { q: ["valor campo lançamento manual", "valor verba lançamento"], a: "Sim. O campo valor deve conter o valor da verba." },
      { q: ["descrição crédito verba", "campo descrição lançamento"], a: "Sim. A descrição deve explicar a que se refere a verba." },
      { q: ["o que colocar descrição", "sugestão descrição verba"], a: "Foi sugerido informar o mês e o ano a que se refere a verba." },
      { q: ["várias verbas mesmo período", "múltiplos lançamentos mesmo período"], a: "Sim. O valor não será sobrescrito, será adicionado." },
      { q: ["quando cadastro manual ocorre", "sextas feiras cadastro", "dia cadastro crédito"], a: "O cadastro dos valores ocorre manualmente todas as sextas-feiras." },
      { q: ["salvar lançamento", "clicar salvar backoffice", "gravar lançamento manual"], a: "Sim. Deve clicar em Salvar para registrar as alterações." },
      { q: ["processo sem gravar", "sem salvar processo segue"], a: "Não. O cadastro ou lançamento precisa ser gravado ou salvo." },
      { q: ["documentação incorreta reprova", "adm reprova devolve representante"], a: "A Administração de Vendas pode reprovar e devolver para ajustes do representante." },
      { q: ["verba concluída quando", "verba aprovada fluxo completo", "quando verba está pronta"], a: "Após todas as aprovações, com OK da Coordenação de Vendas, aguardando o próximo pedido para encontro de contas e pagamento." },

      // CLIENTE — 70 perguntas
      { q: ["como solicitar verba", "pedir verba cliente", "quero uma verba"], a: "A verba deve ser cadastrada no Mercanet pelo representante, na tela Ações de Verbas." },
      { q: ["verba antes da ação", "solicitar antes de fazer"], a: "O processo considera o cadastro após a ação realizada no cliente." },
      { q: ["prazo cadastrar verba cliente", "quantos dias tenho"], a: "Até 30 dias após ocorrer a ação." },
      { q: ["onde verba é cadastrada", "sistema cadastro verba"], a: "No Mercanet, em Menu – Ações de Verbas – Ações de Verbas." },
      { q: ["quem cadastra verba", "responsável cadastro verba"], a: "O representante é responsável pelo cadastro das informações." },
      { q: ["informações necessárias verba", "quais dados preciso", "campos verba"], a: "Empresa, tipo de verba, tipo de ação, data da ação, valor do pagamento, forma de pagamento e anexos." },
      { q: ["preciso informar código cliente", "código cliente obrigatório"], a: "Sim. O código do cliente deve ser informado no cadastro." },
      { q: ["não sei código cliente", "como achar código cliente"], a: "Pode ser usada a lupa ao lado do campo código do cliente para busca." },
      { q: ["razão social automática", "preencher razão social manual"], a: "Ao selecionar o cliente, Razão Social, UF, GA e GR são preenchidos automaticamente." },
      { q: ["preciso escolher empresa verba", "empresa campo obrigatório verba"], a: "Sim. Deve ser selecionada a empresa que fatura para o cliente." },
      { q: ["o que é tipo de verba", "diferença comercial trade verba"], a: "É a classificação da verba como Comercial ou Trade." },
      { q: ["informar ação realizada", "tipo ação campo obrigatório"], a: "Sim. Deve ser selecionado o tipo de ação realizada no cliente." },
      { q: ["posso informar qualquer data", "data livre verba"], a: "Não. O campo permite somente 1 mês anterior à data de lançamento." },
      { q: ["como informo valor verba cliente", "campo valor verba cliente"], a: "No campo de valor do pagamento, informando o valor da verba a ser paga." },
      { q: ["preciso informar como receber", "forma pagamento cliente obrigatório"], a: "Sim. A forma de pagamento da verba deve ser informada." },
      { q: ["preciso enviar documentos verba", "documentos obrigatórios verba cliente"], a: "Sim. Devem ser anexadas as documentações necessárias." },
      { q: ["verba sem documentação segue", "pode processar sem doc"], a: "O processo exige anexar documentação para dar andamento." },
      { q: ["depois de preencher o que acontece", "após cadastro o que ocorre"], a: "O cadastro deve ser gravado e seguirá para aprovação." },
      { q: ["quem aprova primeiro cliente", "primeira aprovação verba cliente"], a: "O primeiro aprovador é o Gestor de Área." },
      { q: ["o que ga analisa", "gestor área verifica o quê"], a: "A documentação inserida." },
      { q: ["ga pode reprovar verba", "gestor área pode negar"], a: "Sim. Ele pode aprovar ou reprovar a ação." },
      { q: ["prazo ga cliente", "quantos dias gestor área aprovação"], a: "Até 7 dias a partir da data de cadastro." },
      { q: ["quem aprova depois ga", "após gestor área cliente"], a: "O Gestor Regional." },
      { q: ["o que gr verifica", "gestor regional analisa o quê"], a: "Ele valida o saldo para reservar o valor e analisa a documentação." },
      { q: ["valor fica reservado", "gr reserva valor minha verba"], a: "Sim. Na etapa do Gestor Regional é feita a reserva do valor, quando há saldo." },
      { q: ["o que acontece sem saldo cliente", "sem saldo verba minha"], a: "A ocorrência pode seguir para dupla aprovação." },
      { q: ["quem aprova sem saldo cliente", "dupla aprovação saldo cliente"], a: "Gestor Nacional de Vendas e Gestor Financeiro." },
      { q: ["sistema avisa falta saldo cliente", "notificação saldo insuficiente"], a: "Sim. O sistema apresenta mensagem informando falta de saldo e valor a acrescer." },
      { q: ["verba cancelada sem saldo", "cancela automaticamente saldo"], a: "Não. Ela pode seguir para dupla aprovação." },
      { q: ["diferença valor creditada cliente", "crédito diferença cliente"], a: "Sim. Com a aprovação da Gestão Nacional, a diferença é automaticamente creditada." },
      { q: ["depois gestão nacional para onde vai cliente", "fluxo gestão nacional cliente"], a: "Vai para aprovação da Administração de Vendas." },
      { q: ["o que adm vendas faz cliente", "administração verifica minha verba"], a: "Valida as documentações." },
      { q: ["adm pode devolver verba cliente", "verba pode voltar para mim"], a: "Sim. Pode reprovar e devolver ao representante para ajustes." },
      { q: ["posso corrigir verba reprovada", "ajustar verba devolvida"], a: "Sim. O representante deve realizar os ajustes necessários." },
      { q: ["prazo adm vendas cliente", "dias administração analisar"], a: "Até 7 dias a partir da data de cadastro." },
      { q: ["quando coordenação entra", "coordenação vendas quando atua"], a: "Após as aprovações anteriores." },
      { q: ["coordenação é última etapa", "última aprovação coordenação cliente"], a: "Sim. É a última aprovação do fluxo." },
      { q: ["depois ok coordenação cliente", "após aprovação final"], a: "A verba fica aguardando a entrada do próximo pedido." },
      { q: ["verba paga imediatamente", "recebo verba na hora"], a: "O processo informa que ficará aguardando o próximo pedido para encontro de contas e pagamento." },
      { q: ["como será feito pagamento verba", "como recebo minha verba"], a: "Por encontro de contas no próximo pedido." },
      { q: ["valor deixa de estar reservado cliente", "reserva encerra cliente"], a: "Na aprovação da Coordenação de Vendas." },
      { q: ["quando valor debitado gestor cliente", "debito gestor quando cliente"], a: "No momento da aprovação final pela Coordenação de Vendas." },
      { q: ["prazo coordenação cliente", "dias coordenação decidir"], a: "Até 7 dias a partir da data de cadastro." },
      { q: ["existe lançamento crédito antes verba", "crédito backoffice cliente"], a: "Sim. O Backoffice realiza lançamento de créditos no Mercanet." },
      { q: ["onde backoffice lança crédito cliente", "menu backoffice cliente"], a: "Em Menu – Ações de Verbas – Lançamentos Manuais em Conta Corrente." },
      { q: ["lançamento permanente ou temporário", "manual permanente"], a: "O documento informa que ficará disponível até a liberação do cálculo automático." },
      { q: ["crédito é comercial ou trade cliente", "tipo crédito cliente"], a: "A conta de investimento pode ser Comercial ou Trade." },
      { q: ["quem recebe crédito manual cliente", "gestor regional recebe cliente"], a: "O Gestor Regional informado no campo representante." },
      { q: ["data lançamento cliente", "o que é data lançamento cliente"], a: "É o início da vigência do crédito liberado." },
      { q: ["data vigência cliente", "vigência crédito cliente"], a: "É a data limite de validade do crédito para lançamento e utilização." },
      { q: ["mais de uma verba mesmo período cliente", "verbas acumulam"], a: "Sim. O valor não será sobrescrito, será adicionado." },
      { q: ["quando créditos cadastrados cliente", "dia crédito disponível"], a: "Todas as sextas-feiras." },
      { q: ["mês ano na descrição verba", "descrição verba cliente"], a: "O documento sugere informar mês e ano na descrição." },
      { q: ["verba reprovada desaparece", "verba reprovada some"], a: "O processo informa que pode voltar ao representante para ajustes necessários." },
      { q: ["quem acompanha documentação verba", "documentação verificada por quem"], a: "Gestor de Área, Gestor Regional e Administração de Vendas analisam documentação em suas etapas." },
      { q: ["prazo cada aprovação", "existe prazo por etapa"], a: "Sim. As etapas citadas têm prazo de até 7 dias a partir da data de cadastro." },
      { q: ["verba depende próximo pedido", "precisa fazer pedido para verba"], a: "Sim. Após OK final, aguarda o próximo pedido para encontro de contas." },
      { q: ["verba impacta conta gestor", "gestor perde saldo verba"], a: "Sim. Ao final, o valor é definitivamente debitado da conta do gestor." },
      { q: ["saldo gestor verificado", "gestor tem saldo verba"], a: "Sim. O Gestor Regional valida saldo para reserva." },
      { q: ["com saldo precisa gestão nacional", "quando gestão nacional não entra"], a: "A Gestão Nacional é acionada quando não há crédito suficiente." },
      { q: ["sem gestor regional como funciona", "não tem gr o que acontece"], a: "O documento informa que, no caso de não ter regional, a falta de crédito na aprovação do Gestor de Área encaminha para Gestão Nacional." },
      { q: ["verba pode ser comercial", "tipo comercial existe verba"], a: "Sim. Comercial é um dos tipos permitidos." },
      { q: ["verba pode ser trade", "tipo trade existe verba"], a: "Sim. Trade é um dos tipos permitidos." },
      { q: ["cadastro precisa ser salvo verba", "gravar obrigatório verba"], a: "Sim. O cadastro deve ser gravado." },
      { q: ["lançamento manual precisa salvar", "salvar backoffice obrigatório"], a: "Sim. Após editar, deve-se clicar em Salvar." },
      { q: ["forma pagamento obrigatória cliente", "cliente informa forma pagamento"], a: "Sim. O cadastro exige forma de pagamento." },
      { q: ["ação vinculada verba cliente", "ação obrigatória verba cliente"], a: "Sim. Deve ser selecionado o tipo de ação realizada no cliente." },
      { q: ["verba passa aprovação interna", "aprovação interna existe verba"], a: "Sim. Existe workflow de aprovações." },
      { q: ["etapas após cadastro verba", "quantas etapas aprovação verba"], a: "Gestor de Área, Gestor Regional, Administração de Vendas, Gestão Nacional quando aplicável, e Coordenação de Vendas." },
      { q: ["quando verba aprovada para pagamento", "verba considerada aprovada quando"], a: "Após o OK da Coordenação de Vendas, ficando aguardando o próximo pedido para encontro de contas e pagamento." },
    ],
  },

  trocas: {
    name: "Agente de Trocas",
    color: "#059669",
    emoji: "🔄",
    subtitle: "Avaria, Vencido, Baixo Giro, Fora de Linha",
    greeting: "Olá! Sou o Agente de Trocas da Embelleze. Posso te ajudar com avarias, vencidos, baixo giro e itens fora de linha. Como posso ajudar?",
    suggested: ["Qual tipo de troca posso solicitar?", "Avaria identificada depois da entrega é aceita?", "O que é baixo giro?", "Quem aprova a troca?"],
    qa: [
      // VENDEDOR — 70 perguntas
      { q: ["tipo solicitação troca", "avaria vencido baixo giro fora linha", "qual tipo troca"], a: "A política trata de quatro situações de troca: avaria, vencido, baixo giro e fora de linha." },
      { q: ["avaria ocorreu ato entrega vendedor", "avaria entrega vendedor"], a: "Só será considerada avaria ocorrida no ato da entrega." },
      { q: ["existe evidência avaria vendedor", "evidência necessária avaria"], a: "É necessária evidência da ocorrência por foto ou filmagem." },
      { q: ["foto filmagem enviada avaria", "enviar foto avaria vendedor"], a: "Deve haver foto ou filmagem comprovando a ocorrência." },
      { q: ["nota fiscal devolução avaria vendedor", "nf devolução avaria"], a: "Para avaria, a política exige nota fiscal de devolução." },
      { q: ["nota fiscal origem avaria vendedor", "nf origem avaria"], a: "O processo é válido somente para clientes que apresentarem NF de origem." },
      { q: ["transportadora debitada avaria", "débito transportadora avaria vendedor"], a: "No caso de avaria, deve-se proceder débito da transportadora." },
      { q: ["produto é vencido vendedor", "item vencido identificado"], a: "Produto vencido é item acima do prazo de validade considerado." },
      { q: ["validade considerar produto vendedor", "prazo validade skus"], a: "36 meses para todos os SKUs, exceto Henê." },
      { q: ["item é henê vendedor", "henê prazo validade vendedor"], a: "Para Henê, a validade considerada é de 24 meses." },
      { q: ["vencimento dentro limite vendedor", "aceita vencido até quantos meses"], a: "Só são aceitos produtos com no máximo 2 meses de vencimento após a validade." },
      { q: ["foto vencidos palavra chave vendedor", "palavra chave mês vencido vendedor"], a: "Para aprovação, é necessária foto dos itens vencidos com a palavra-chave do mês." },
      { q: ["mercadoria vencida será devolvida vendedor", "devolução mercadoria vencida vendedor"], a: "Se for devolvida, são necessárias NF de origem e NF de devolução." },
      { q: ["nf origem mercadoria devolvida vendedor", "nota fiscal origem devolução vendedor"], a: "Para mercadoria devolvida, é necessária NF de origem." },
      { q: ["nf devolução mercadoria vendedor", "nota fiscal devolução vendedor"], a: "Para mercadoria devolvida, é necessária NF de devolução." },
      { q: ["mercadoria vencida será descartada vendedor", "descarte mercadoria vencida vendedor"], a: "Se for descartada, exige NF de baixa da mercadoria." },
      { q: ["nf baixa descarte vendedor", "nota fiscal baixa vendedor"], a: "Para descarte, é necessária NF de baixa da mercadoria." },
      { q: ["documentos local descarte vendedor", "comprovação descarte vendedor"], a: "Para descarte, são necessários documentos do local onde os produtos foram descartados." },
      { q: ["bonificação preço vigente vendedor", "pagamento bonificação preço atual"], a: "O pagamento será via bonificação considerando o preço vigente." },
      { q: ["bonificação itens obrigatórios guia mix vendedor", "guia mix bonificação vendedor"], a: "A bonificação será feita com base nos itens obrigatórios e lançamentos do Guia Mix." },
      { q: ["família bonificada 30% vendedor", "limite família 30 por cento vendedor"], a: "Cada família bonificada não pode ultrapassar 30% do valor total da bonificação." },
      { q: ["bonificação próximo pedido vendedor", "quando recebo bonificação vendedor"], a: "A bonificação sempre seguirá com o próximo pedido do cliente." },
      { q: ["descarte ou retorno embelleze vendedor", "verificar possibilidade descarte vendedor"], a: "A política prevê verificar a possibilidade de descarte pelo cliente ou retorno da mercadoria." },
      { q: ["processo submetido avaliação interna vendedor", "aprovação interna troca vendedor"], a: "O processo acontece mediante avaliação e aprovação interna." },
      { q: ["item é baixo giro vendedor", "definição baixo giro vendedor"], a: "Baixo giro é item que o cliente deixou de comprar no sell in e, nos 4 meses seguintes, o sell out não reduziu o estoque." },
      { q: ["cliente deixou comprar sell in vendedor", "sell in zerado baixo giro vendedor"], a: "Essa é uma condição para caracterizar baixo giro." },
      { q: ["sell out insuficiente 4 meses vendedor", "sell out não reduziu estoque vendedor"], a: "Sim, essa condição precisa estar presente para baixo giro." },
      { q: ["foto baixo giro palavra chave vendedor", "foto itens baixo giro vendedor"], a: "É necessário enviar foto dos itens com a palavra-chave do mês." },
      { q: ["documentação quantidade baixo giro vendedor", "comprovar quantidade item vendedor"], a: "A documentação do cliente deve comprovar a quantidade do item." },
      { q: ["4 últimas compras comprovadas vendedor", "comprovação compras baixo giro vendedor"], a: "É exigida comprovação das 4 últimas compras do cliente do item." },
      { q: ["print cockpit bi vendedor", "cockpit bi baixo giro vendedor"], a: "A comprovação deve incluir print do item no Cockpit BI." },
      { q: ["relatório sell out 4 meses vendedor", "sell out relatório vendedor"], a: "É necessário relatório de sell out dos últimos 4 meses." },
      { q: ["estoque acima 100 dias vendedor", "100 dias estoque vendedor"], a: "Deve haver comprovação do nível de estoque acima de 100 dias ao final dos 4 meses." },
      { q: ["bonificação baixo giro preço vigente vendedor", "pagamento baixo giro vendedor"], a: "Sim. O pagamento será via bonificação considerando o preço vigente." },
      { q: ["bonificação baixo giro guia mix vendedor", "guia mix baixo giro vendedor"], a: "Sim. Será feita com base nos itens obrigatórios e lançamentos do Guia Mix." },
      { q: ["família bonificada baixo giro 30% vendedor", "30% família baixo giro vendedor"], a: "Cada família bonificada não pode ultrapassar 30% do valor total da bonificação." },
      { q: ["bonificação baixo giro próximo pedido vendedor", "quando recebo baixo giro vendedor"], a: "Sim. Sempre seguirá com o próximo pedido do cliente." },
      { q: ["itens baixo giro pdv vendedor", "ação pdv baixo giro vendedor"], a: "Devem ser usados em ações no PDV, como compre ganhe, estoura balão e cesta de produtos." },
      { q: ["print bi sell in 4 meses vendedor", "bi vendas sell in vendedor"], a: "A política exige print do BI com as vendas sell in dos últimos 4 meses do item." },
      { q: ["processo baixo giro avaliação interna vendedor", "aprovação interna baixo giro vendedor"], a: "O processo acontece mediante avaliação e aprovação interna." },
      { q: ["item fora de linha vendedor", "definição fora de linha vendedor"], a: "Fora de linha é item inativo para Embelleze, sem nova compra pelo cliente e com estoque elevado." },
      { q: ["item inativo embelleze vendedor", "inativo fora de linha vendedor"], a: "Essa é uma condição para item fora de linha." },
      { q: ["cliente deixou comprar fora linha vendedor", "sem compra fora de linha vendedor"], a: "Para fora de linha, o cliente não realiza mais compra do item." },
      { q: ["cliente estoque elevado fora linha vendedor", "estoque alto fora linha vendedor"], a: "O estoque elevado é parte da definição de fora de linha." },
      { q: ["foto fora linha palavra chave vendedor", "foto item fora linha vendedor"], a: "É necessária foto dos itens com a palavra-chave do mês." },
      { q: ["documentação quantidade fora linha vendedor", "comprovar quantidade fora linha vendedor"], a: "É necessária documentação do cliente para comprovar a quantidade." },
      { q: ["4 compras fora linha comprovadas vendedor", "últimas compras fora linha vendedor"], a: "É exigida comprovação das últimas 4 compras do cliente do item." },
      { q: ["print cockpit fora linha vendedor", "cockpit fora de linha vendedor"], a: "A comprovação deve incluir print do item no Cockpit." },
      { q: ["estoque item dias fora linha vendedor", "dias estoque fora linha vendedor"], a: "Para fora de linha, deve ser informado o estoque do item do cliente em dias." },
      { q: ["bonificação fora linha preço vigente vendedor", "pagamento fora linha vendedor"], a: "Sim. O pagamento será via bonificação considerando o preço vigente." },
      { q: ["bonificação fora linha guia mix vendedor", "guia mix fora linha vendedor"], a: "Sim. Será feita com base nos itens mandatórios e lançamentos do Guia Mix." },
      { q: ["família bonificada fora linha 30% vendedor", "30% família fora linha vendedor"], a: "Cada família bonificada não pode ultrapassar 30% do valor total da bonificação." },
      { q: ["bonificação fora linha próximo pedido vendedor", "quando recebo fora linha vendedor"], a: "Sim. Sempre seguirá com o próximo pedido do cliente." },
      { q: ["itens fora linha pdv vendedor", "ação pdv fora linha vendedor"], a: "Devem ser usados em ações como compre ganhe, estoura balão e cesta de produtos." },
      { q: ["chegou estágio fora linha vendedor", "evitar fora de linha vendedor"], a: "A política sinaliza evitar que se chegue nesse estágio com o cliente." },
      { q: ["cliente dentro limite bonificação vendedor", "percentual máximo cliente vendedor"], a: "Deve ser monitorado o percentual máximo por cliente versus faturamento em 12 meses." },
      { q: ["cliente perfumaria vendedor", "perfumaria limite vendedor"], a: "Para perfumarias, o limite indicado é até 1% do faturamento em 12 meses." },
      { q: ["demais canais limite vendedor", "outros canais limite bonificação vendedor"], a: "Para demais canais, o limite indicado é até 0,3% do faturamento em 12 meses." },
      { q: ["limite regional vendedor", "regional 0,3% vendedor"], a: "O regional tem limite de até 0,3% do faturado." },
      { q: ["bi bonificações consultado vendedor", "monitoramento bi vendedor"], a: "A política cita o BI de bonificações como forma de monitoramento por cliente." },
      { q: ["adm vendas check notas vendedor", "administração notas troca vendedor"], a: "A hierarquia indica ADM Vendas para check de notas." },
      { q: ["adm vendas check imagens vendedor", "administração imagens troca vendedor"], a: "A hierarquia indica ADM Vendas para check de imagens." },
      { q: ["adm vendas check documentação vendedor", "administração documentação troca vendedor"], a: "A hierarquia indica ADM Vendas para check de documentação." },
      { q: ["valor até 500 vendedor", "faixa até 500 troca vendedor"], a: "A política apresenta faixa de aprovação até R$ 500." },
      { q: ["valor 501 a 1000 vendedor", "faixa 501 a 1000 troca vendedor"], a: "A política apresenta faixa de aprovação de R$ 501 a R$ 1.000." },
      { q: ["valor 1001 a 5000 vendedor", "faixa 1001 a 5000 troca vendedor"], a: "A política apresenta faixa de aprovação de R$ 1.001 a R$ 5.000." },
      { q: ["valor acima 5001 vendedor", "faixa acima 5001 troca vendedor"], a: "A política apresenta faixa acima de R$ 5.001." },
      { q: ["aprovação gerente regional troca vendedor", "gr aprova troca vendedor"], a: "A hierarquia apresentada inclui Gerente Regional em faixas de aprovação." },
      { q: ["aprovação diretor comercial troca vendedor", "diretor aprova troca vendedor"], a: "A hierarquia apresentada inclui Diretor Comercial em faixas de aprovação." },
      { q: ["documentação suficiente troca vendedor", "documentação completa troca vendedor"], a: "A solicitação deve conter notas, imagens e documentação conforme o tipo de troca." },

      // CLIENTE — 70 perguntas
      { q: ["quais tipos troca posso solicitar", "tipos troca cliente"], a: "A política contempla avaria, vencido, baixo giro e fora de linha." },
      { q: ["mercadoria avariada aceita cliente", "avaria aceita cliente"], a: "Sim, desde que a avaria tenha ocorrido no ato da entrega." },
      { q: ["avaria depois entrega aceita cliente", "avaria após entrega cliente"], a: "A política considera apenas avaria ocorrida no ato da entrega." },
      { q: ["preciso provar avaria cliente", "evidência avaria cliente"], a: "Sim. É necessária evidência da ocorrência por foto ou filmagem." },
      { q: ["preciso nf devolução avaria cliente", "nota fiscal devolução avaria cliente"], a: "Sim. A nota fiscal de devolução é exigida." },
      { q: ["preciso nf origem cliente", "nota fiscal origem obrigatória cliente"], a: "Sim. O processo é válido somente para clientes que apresentarem NF de origem." },
      { q: ["quem debitado avaria cliente", "quem paga avaria cliente"], a: "A política informa que deve ser feito débito da transportadora." },
      { q: ["o que é produto vencido cliente", "definição vencido cliente"], a: "Item acima do prazo de validade do produto." },
      { q: ["qual prazo validade considerado cliente", "validade produto cliente"], a: "36 meses para todos os SKUs, exceto Henê." },
      { q: ["prazo validade henê cliente", "henê cliente validade"], a: "Para Henê, são considerados 24 meses." },
      { q: ["produto vencido mais 2 meses aceito cliente", "vencido 2 meses aceito cliente"], a: "Não. Só são aceitos produtos com no máximo 2 meses de vencimento após a validade." },
      { q: ["preciso enviar foto vencidos cliente", "foto produtos vencidos cliente"], a: "Sim. A foto deve conter a palavra-chave do mês." },
      { q: ["o que enviar devolver vencido cliente", "documentos devolução vencido cliente"], a: "NF de origem da mercadoria e NF de devolução da mercadoria." },
      { q: ["o que enviar descartar vencido cliente", "documentos descarte vencido cliente"], a: "NF de baixa da mercadoria e documentos do local onde os produtos foram descartados." },
      { q: ["posso descartar mercadoria cliente", "descarte no cliente possível"], a: "A política informa que será verificada a possibilidade de descarte pelo cliente ou retorno da mercadoria para a Embelleze." },
      { q: ["troca vencido aprovada automaticamente cliente", "aprovação automática vencido cliente"], a: "Não. O processo acontece mediante avaliação e aprovação interna." },
      { q: ["como pago vencido cliente", "pagamento vencido cliente"], a: "Via bonificação, considerando o preço vigente." },
      { q: ["bonificação em dinheiro cliente", "bonificação dinheiro ou produto cliente"], a: "O processo informa pagamento via bonificação." },
      { q: ["quando recebo bonificação cliente", "prazo bonificação cliente"], a: "A bonificação sempre seguirá com o próximo pedido do cliente." },
      { q: ["bonificação qualquer produto cliente", "o que vem na bonificação cliente"], a: "Será feita com base nos itens obrigatórios e lançamentos do Guia Mix." },
      { q: ["limite por família produto cliente", "30% família cliente"], a: "Cada família bonificada não pode ultrapassar 30% do valor total da bonificação." },
      { q: ["o que é baixo giro cliente", "definição baixo giro cliente"], a: "É item que o cliente deixou de comprar no sell in e, nos 4 meses seguintes, o sell out não reduziu o estoque." },
      { q: ["baixo giro depende sell in cliente", "sell in baixo giro cliente"], a: "Sim. O cliente deve ter deixado de comprar o item no sell in." },
      { q: ["baixo giro depende sell out cliente", "sell out baixo giro cliente"], a: "Sim. O sell out dos 4 meses subsequentes deve ser insuficiente para reduzir o estoque." },
      { q: ["preciso foto baixo giro cliente", "foto itens baixo giro cliente"], a: "Sim. Foto dos itens com a palavra-chave do mês." },
      { q: ["preciso comprovar quantidade estoque cliente", "comprovação quantidade cliente"], a: "Sim. É exigida documentação do cliente para comprovação da quantidade do item." },
      { q: ["preciso comprovar compras anteriores cliente", "comprovação compras cliente"], a: "Sim. Deve comprovar as 4 últimas compras do cliente do item." },
      { q: ["como comprovo compras do item cliente", "como provar compras cliente"], a: "Com print do item no Cockpit BI." },
      { q: ["preciso relatório sell out cliente", "sell out relatório cliente"], a: "Sim. Relatório de sell out dos últimos 4 meses." },
      { q: ["comprovar estoque 100 dias cliente", "100 dias estoque cliente"], a: "Sim. Deve comprovar nível de estoque acima de 100 dias ao final dos 4 meses." },
      { q: ["como pago baixo giro cliente", "pagamento baixo giro cliente"], a: "Via bonificação considerando o preço vigente." },
      { q: ["bonificação baixo giro próximo pedido cliente", "quando recebo baixo giro cliente"], a: "Sim. Sempre seguirá com o próximo pedido do cliente." },
      { q: ["bonificação baixo giro guia mix cliente", "guia mix baixo giro cliente"], a: "Sim. Será feita com base nos itens obrigatórios e lançamentos do Guia Mix." },
      { q: ["30% família baixo giro cliente", "limite família baixo giro cliente"], a: "Sim. Cada família bonificada não pode ultrapassar 30% do valor total." },
      { q: ["o que fazer itens baixo giro cliente", "usar itens baixo giro cliente"], a: "Devem ser usados em ações no PDV, como compre ganhe, estoura balão e cesta de produtos." },
      { q: ["baixo giro depende aprovação interna cliente", "aprovação interna baixo giro cliente"], a: "Sim. O processo acontece mediante avaliação e aprovação interna." },
      { q: ["o que é item fora de linha cliente", "definição fora linha cliente"], a: "É item inativo para Embelleze, que o cliente não compra mais e ainda possui estoque elevado." },
      { q: ["produto fora linha pode entrar política cliente", "fora linha aceito cliente"], a: "Sim, desde que atenda à definição e documentação exigida." },
      { q: ["preciso foto fora linha cliente", "foto item fora linha cliente"], a: "Sim. Foto dos itens com a palavra-chave do mês." },
      { q: ["preciso comprovar quantidade fora linha cliente", "quantidade fora linha cliente"], a: "Sim. É necessária documentação do cliente para comprovar a quantidade." },
      { q: ["preciso comprovar compras fora linha cliente", "últimas compras fora linha cliente"], a: "Sim. Deve comprovar as últimas 4 compras do cliente do item." },
      { q: ["como comprovo compras fora linha cliente", "print cockpit fora linha cliente"], a: "Com print do item no Cockpit." },
      { q: ["preciso informar estoque dias fora linha cliente", "estoque em dias fora linha cliente"], a: "Sim. A política exige o estoque do item do cliente em dias." },
      { q: ["como pago fora linha cliente", "pagamento fora linha cliente"], a: "Via bonificação considerando o preço vigente." },
      { q: ["bonificação fora linha guia mix cliente", "guia mix fora linha cliente"], a: "Sim. Será feita com base nos itens mandatórios e lançamentos do Guia Mix." },
      { q: ["limite família fora linha cliente", "30% família fora linha cliente"], a: "Sim. Cada família bonificada não pode ultrapassar 30% do valor total da bonificação." },
      { q: ["bonificação fora linha próximo pedido cliente", "quando recebo fora linha cliente"], a: "Sim. Sempre seguirá com o próximo pedido do cliente." },
      { q: ["o que fazer itens fora linha cliente", "usar itens fora linha pdv cliente"], a: "Devem ser usados em ações no PDV, como compre ganhe, estoura balão e cesta de produtos." },
      { q: ["fora linha empresa quer evitar cliente", "evitar fora linha cliente"], a: "Sim. A política destaca evitar chegar nesse estágio com o cliente." },
      { q: ["existe limite máximo bonificação cliente", "limite bonificação por cliente"], a: "Sim. Deve ser monitorado o percentual máximo versus faturamento em 12 meses." },
      { q: ["limite perfumaria cliente", "1% perfumaria cliente"], a: "Até 1% do faturamento em 12 meses." },
      { q: ["limite demais canais cliente", "0,3% demais canais cliente"], a: "Até 0,3% do faturamento em 12 meses." },
      { q: ["limite regional cliente", "0,3% regional cliente"], a: "Até 0,3% do faturado." },
      { q: ["como empresa monitora bonificações cliente", "monitoramento bonificação cliente"], a: "A política indica o BI de bonificações." },
      { q: ["quem confere notas cliente", "check notas troca cliente"], a: "A Administração de Vendas faz check das notas." },
      { q: ["quem confere imagens cliente", "check imagens troca cliente"], a: "A Administração de Vendas faz check das imagens." },
      { q: ["quem confere documentação troca cliente", "check documentação troca cliente"], a: "A Administração de Vendas faz check da documentação." },
      { q: ["existe hierarquia aprovação por valor cliente", "aprovação por faixa valor cliente"], a: "Sim. A política apresenta hierarquia por valor mensal." },
      { q: ["quais faixas valor política troca cliente", "faixas aprovação troca cliente"], a: "Até R$ 500; R$ 501 a R$ 1.000; R$ 1.001 a R$ 5.000; acima de R$ 5.001." },
      { q: ["representante participa processo troca cliente", "representante troca cliente"], a: "A hierarquia apresentada inclui o representante." },
      { q: ["gerente regional pode aprovar troca cliente", "gr aprova troca cliente"], a: "Sim. A hierarquia apresentada inclui Gerente Regional." },
      { q: ["diretor comercial pode aprovar troca cliente", "diretor aprova troca cliente"], a: "Sim. A hierarquia apresentada inclui Diretor Comercial." },
      { q: ["adm vendas participa todas faixas cliente", "adm todas faixas cliente"], a: "A política mostra ADM Vendas realizando check de notas, imagens e documentação." },
      { q: ["faltar foto processo aprovado cliente", "sem foto troca aprovada cliente"], a: "A política exige foto ou evidência conforme o tipo de ocorrência." },
      { q: ["faltar nf origem avaria segue cliente", "sem nf origem avaria cliente"], a: "Não. O processo é válido somente para clientes que apresentarem NF de origem." },
      { q: ["faltar relatório sell out baixo giro cliente", "sem sell out incompleto cliente"], a: "Sim. O relatório de sell out dos últimos 4 meses é necessário." },
      { q: ["faltar print cockpit baixo giro cliente", "sem cockpit incompleto cliente"], a: "Sim. A política exige print do item no Cockpit BI." },
      { q: ["estoque não acima 100 dias é baixo giro cliente", "100 dias condição baixo giro cliente"], a: "A política exige comprovação do estoque acima de 100 dias ao final dos 4 meses." },
      { q: ["item ainda ativo fora linha cliente", "ativo não é fora linha cliente"], a: "Fora de linha é item inativo para a Embelleze." },
      { q: ["quando solicitação completa para análise cliente", "documentação completa troca cliente"], a: "Quando a solicitação tiver a documentação exigida para o tipo de troca, notas, imagens, comprovações e estiver dentro das regras da política." },
    ],
  },

  devolucao: {
    name: "Agente de Devolução",
    color: "#DC2626",
    emoji: "↩️",
    subtitle: "Retorno de Mercadorias",
    greeting: "Olá! Sou o Agente de Devolução da Embelleze. Posso te ajudar sobre processos de devolução de mercadorias. Como posso ajudar?",
    suggested: ["Como solicitar devolução?", "Preciso de NF para devolver?", "Quanto tempo tenho?", "A devolução impacta minha verba?"],
    qa: [
      { q: ["o que é devolução", "como funciona devolução"], a: "Devolução é o retorno de mercadoria à Embelleze. Pode ocorrer por: avaria no ato da entrega, produto vencido, item fora de linha, ou outras situações previstas na política." },
      { q: ["devolução avaria", "devolver produto avariado"], a: "Devolução por avaria: só aceita no ato da entrega. Necessário: evidência (foto/filmagem), NF de devolução e débito na transportadora." },
      { q: ["nf de devolução obrigatória", "nota fiscal devolução"], a: "A Nota Fiscal de Devolução é documento obrigatório. Deve ser emitida pelo cliente devolvendo a mercadoria para a Embelleze." },
      { q: ["devolução vencido retorno físico", "devolver produto vencido fisicamente"], a: "Para devolução de produto vencido por retorno físico: NF de origem da mercadoria + NF de devolução." },
      { q: ["descarte produto vencido devolução", "não devolve descarta vencido"], a: "Em vez de devolver, o produto vencido pode ser descartado. Necessário: NF de baixa + documentos do local de descarte." },
      { q: ["devolução impacto verba", "devolução afeta verba", "cancelamento nf verba"], a: "Havendo cancelamento/devolução de NF, o valor da verba SERÁ DEBITADO DO CLIENTE/GESTOR no mês da entrada." },
      { q: ["prazo aceite devolução", "quando pode devolver prazo"], a: "Avaria: apenas no ato da entrega. Vencido: produto com no máximo 2 meses além do prazo de validade. Outros casos: mediante avaliação interna." },
      { q: ["transportadora responsável devolução", "débito transportadora devolução"], a: "Em caso de avaria na entrega, deve-se proceder o débito da transportadora. O custo da avaria recai sobre ela." },
      { q: ["devolução sem nf origem", "sem nota fiscal origem devolução"], a: "O processo de devolução é válido somente para clientes que apresentarem NF de origem." },
      { q: ["como solicitar devolução passo a passo", "processo devolução passo a passo"], a: "Para solicitar: 1) Identifique o motivo; 2) Reúna a NF de origem; 3) Fotos com palavra chave; 4) Emita a NF de devolução; 5) Submeta para aprovação conforme hierarquia de valores." },
      { q: ["devolução compensação bonificação", "devolveu recebe bonificação"], a: "Para vencidos devolvidos, a compensação é feita via bonificação pelo preço vigente, com base nos itens obrigatórios do Guia Mix." },
      { q: ["nf de baixa devolução", "nota fiscal baixa descarte"], a: "A NF de Baixa é emitida quando o produto é descartado. Comprova que o produto foi dado baixa no estoque do cliente." },
      { q: ["documentos local descarte devolução", "comprovação local descarte"], a: "Para mercadoria descartada, além da NF de baixa, são necessários documentos do local onde os produtos foram descartados." },
      { q: ["quem aprova devolução hierarquia", "hierarquia aprovação devolução"], a: "Hierarquia por valor: ATÉ R$500: ADM Vendas; R$501-R$1.000: ADM Vendas + GR; R$1.001-R$5.000: ADM Vendas + GR + Diretor Comercial; ACIMA R$5.001: ADM Vendas + GR + Sergio Fernandes." },
      { q: ["devolução negada motivos", "quando devolução não aceita"], a: "Devolução pode ser negada quando: avaria não no ato da entrega; vencido há mais de 2 meses; documentação incompleta; sem NF de origem; limite percentual atingido." },
      { q: ["devolução e protesto cliente", "abatimento indevido devolução"], a: "Se o cliente fizer abatimento/devolução indevidamente sem autorização, poderá ser protestado." },
      { q: ["bonificação devolução próximo pedido", "quando bonificação devolução"], a: "A bonificação compensatória sempre seguirá com o próximo pedido do cliente após aprovação completa." },
      { q: ["foto filmagem avaria devolução", "como registrar avaria devolução"], a: "Para avaria: tire fotos ou grave um vídeo no momento da entrega, mostrando claramente o dano. Esse registro é a evidência obrigatória." },
      { q: ["30% família devolução", "limite família devolução bonificação"], a: "Em qualquer tipo de troca/devolução compensada por bonificação, cada família não pode ultrapassar 30% do valor total da bonificação." },
      { q: ["processo avaliação interna devolução", "aprovação interna devolução"], a: "O processo acontece mediante avaliação e aprovação interna da Embelleze. Não é automático." },
      { q: ["devolução urgente avaria", "urgência avaria devolução"], a: "Para avaria: urgência máxima — deve ser registrada no ato da entrega. Acione imediatamente o Representante e registre tudo com foto/vídeo." },
    ],
  },

  prorrogacao: {
    name: "Agente de Prorrogação",
    color: "#D97706",
    emoji: "📅",
    subtitle: "Prazos & Vencimentos",
    greeting: "Olá! Sou o Agente de Prorrogação da Embelleze. Posso te ajudar sobre prorrogação de prazos, vencimentos e condições especiais. Como posso ajudar?",
    suggested: ["Como solicitar prorrogação?", "O prazo de verba pode ser prorrogado?", "O que acontece se o prazo vencer?", "Quando o crédito do 1º TRI expira?"],
    qa: [
      { q: ["o que é prorrogação", "definição prorrogação"], a: "Prorrogação é a extensão do prazo de pagamento ou vencimento de títulos/duplicatas do cliente com a Embelleze. Exige aprovação formal e não é concedida automaticamente." },
      { q: ["como solicitar prorrogação", "pedir prorrogação prazo"], a: "A solicitação deve ser feita formalmente pelo Representante Comercial junto ao GA e GR, com justificativa, prazo solicitado e plano de regularização." },
      { q: ["prorrogação automática existe", "prazo prorrogado automaticamente"], a: "NÃO existe prorrogação automática. O cliente NÃO pode fazer abatimentos ou prorrogações por conta própria. Se fizer isso, poderá ser protestado." },
      { q: ["protesto cliente prorrogação", "quando cliente é protestado prorrogação"], a: "O cliente pode ser protestado se fizer abatimentos em duplicatas sem autorização, prorrogações unilaterais ou qualquer ação financeira não acordada." },
      { q: ["verba prazo prorrogável", "prazo verba pode prorrogar"], a: "O prazo de validade das verbas NÃO é prorrogável. Verbas com estouro de tempo são suspensas independente de qualquer negociação." },
      { q: ["saldo trimestre expirou", "crédito zerado trimestre"], a: "O saldo do 1º Trimestre expira em 30/04/24. Após essa data, é zerado automaticamente. Não há prorrogação de saldo entre trimestres." },
      { q: ["suspensão 60 dias ocorrência", "60 dias sem etapas ocorrência"], a: "A ocorrência é suspensa em até 60 dias após cadastro do saldo, caso as etapas não sejam cumpridas. Esse prazo não é prorrogável." },
      { q: ["verba expirada pode reativar", "verba suspensa reativar"], a: "Verbas suspensas por estouro de tempo são zeradas e NÃO podem ser reativadas. É fundamental cumprir os prazos dentro do trimestre vigente." },
      { q: ["prazo validade crédito verba", "até quando usar crédito verba"], a: "O crédito de verba fica válido até Abr/2024 (1º trimestre de 2024). O prazo máximo de cadastro de ocorrência é até 15/04/24." },
      { q: ["urgência prazo vencendo", "prazo urgente verba"], a: "Se o prazo está vencendo: acione IMEDIATAMENTE o Representante Comercial e GA. Escale para GR se necessário. Prazo vencido = perda da verba. Não espere!" },
      { q: ["carryover saldo trimestre", "saldo transferido trimestre"], a: "NÃO há transferência de saldo entre trimestres. O saldo não utilizado é zerado. Um novo saldo é disponibilizado para o trimestre seguinte." },
      { q: ["prorrogação não existe automático resumo", "resumo prorrogação"], a: "Na Embelleze, NÃO existe prorrogação automática de nenhum prazo. Todo prazo que vence sem ação é definitivamente encerrado. A gestão ativa dos prazos é obrigatória." },
      { q: ["ga gr prazo aprovação 10 dias", "10 dias aprovação gestor prorrogação"], a: "GA e GR têm até 10 dias após o cadastro da ação para aprovar (verbas comerciais). Para PESC e Trade, o prazo é de 7 dias." },
      { q: ["data ação retroativa mercanet", "lançar ação passada mercanet"], a: "O campo 'Data de Ação' no Mercanet permite selecionar somente 1 mês anterior. Ações mais antigas não podem ser cadastradas retroativamente." },
      { q: ["cliente quando pode pedir prazo especial", "condição especial prazo cliente"], a: "O cliente pode solicitar condições especiais de prazo através do Representante Comercial, que levará ao GR e ao Crédito e Cobrança. Cada caso é analisado individualmente." },
      { q: ["encontro contas adiar", "adiar encontro de contas"], a: "O encontro de contas ocorre no primeiro pedido após aprovação da ADM de Vendas. Não é possível adiar indefinidamente — acontece no próximo pedido faturado." },
      { q: ["crédito semanal sexta", "quando crédito disponível semanal"], a: "Os créditos de verbas comerciais são disponibilizados toda sexta-feira." },
      { q: ["prazo máximo cadastro 1 tri", "15 abril prazo máximo"], a: "O prazo máximo de cadastro de ocorrência do 1º trimestre é até 15/04/24." },
      { q: ["monitorar prazos como", "como acompanhar prazos verba"], a: "Monitore semanalmente as ocorrências em aberto no MERCANET. Acompanhe as aprovações pendentes por GA e GR. Controle o calendário de prazos do trimestre ativamente." },
      { q: ["prorrogação força maior evento", "evento imprevisto prazo especial"], a: "Situações de força maior podem ser levadas ao GR/GN para avaliação especial. Não há garantia de prorrogação — cada caso é analisado com justificativa formal." },
    ],
  },
};

export function findAnswer(agentKey, question) {
  const agent = KNOWLEDGE[agentKey];
  if (!agent) return null;
  const q = question
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");
  let bestMatch = null;
  let bestScore = 0;
  for (const entry of agent.qa) {
    for (const keyword of entry.q) {
      const kw = keyword.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
      const words = kw.split(" ").filter((w) => w.length > 3);
      let score = 0;
      if (q.includes(kw)) score = 100;
      else { for (const w of words) { if (q.includes(w)) score += 20; } }
      if (score > bestScore) { bestScore = score; bestMatch = entry.a; }
    }
  }
  return bestScore >= 20 ? bestMatch : null;
}
