export const KNOWLEDGE = {
  verbas: {
    name: "Agente de Verbas",
    color: "#7C3AED",
    emoji: "💰",
    subtitle: "Comercial & Trade",
    greeting: "Olá! Sou o Agente de Verbas da Embelleze. Posso te ajudar com tudo sobre verbas comerciais e trade. Como posso ajudar?",
    suggested: ["O que é uma verba?", "Quando a verba é creditada?", "Como cadastro uma verba?", "Qual o prazo de validade do crédito?"],
    qa: [
      { q: ["o que é verba", "conceito de verba", "definição verba"], a: "Verba é um aporte financeiro concedido pela Embelleze a varejistas e atacados com o objetivo de ALAVANCAR seus negócios, gerando incremento de sell out, sell in, positivação do mix de SKUs e maior visibilidade das marcas." },
      { q: ["tipos de verba", "quais verbas existem", "que tipos de verba"], a: "Existem dois tipos: (1) VERBA COMERCIAL — regional, gerada sob faturamento das vendas, permite autonomia e agilidade ao time de vendas. (2) VERBA TRADE — nacional, direcionada pelo time de Trade de acordo com a estratégia nacional de crescimento por canal." },
      { q: ["verba comercial exemplos", "o que é verba comercial"], a: "Verbas Comerciais incluem: Ações Promocionais/Rebaixa de Preço, Treinamentos, Aniversários, Inaugurações, Cadastro de Novos SKUs, Compre e Ganhe, Encartes Promocionais, Pontos Extra e outros." },
      { q: ["verba trade exemplos", "o que é verba trade"], a: "Verbas Trade incluem: Campanhas de Trade, Programas de Trade, Eventos Nacionais, Eventos Regionais, Planos de Negócios e JBPs." },
      { q: ["quanto é a verba comercial", "percentual verba comercial", "1,5%"], a: "A verba comercial é de 1,5% sobre o faturamento. Além disso, existe o Plano 100! que oferece 2% de Sell In + 2% de combo." },
      { q: ["plano 100", "2% sell in", "2% combo"], a: "O Plano 100! oferece 2%+2%: o 2% de Sell In e os 2% do combo são aportados APENAS se o cliente atingir mínimo de 90% da meta." },
      { q: ["quando verba é creditada", "prazo crédito verba", "sexta"], a: "As verbas comerciais são creditadas semanalmente, às sextas-feiras. Sandra Irene levanta o valor faturado e disponibiliza o crédito no conta corrente do GA/GR no MERCANET." },
      { q: ["como lançar verba no mercanet", "sistema verba", "cadastrar verba"], a: "No MERCANET: Menu > Ações de Verbas > Ações de Verbas. Clique em NOVO, informe o cliente, empresa, tipo de verba, tipo de ação, data, valor, forma de pagamento e anexe a documentação." },
      { q: ["prazo cadastro verba", "quantos dias para cadastrar"], a: "O representante tem até 30 dias após ocorrer a ação para cadastrar as verbas. O prazo MÁXIMO de cadastro de ocorrência do 1º trimestre é até 15/04/24." },
      { q: ["quem aprova verba", "fluxo aprovação"], a: "O fluxo de aprovação é: 1) Gestor de Área (até 7 dias); 2) Gestor Regional (até 7 dias); 3) ADM de Vendas; 4) Coordenação de Vendas. Para valores acima de 50k, precisa da aprovação do JOMAR." },
      { q: ["aprovação gestor área", "ga aprovação"], a: "O Gestor de Área é o primeiro aprovador. Analisa a documentação e aprova ou reprova. Tem até 7 dias a partir da data de cadastro." },
      { q: ["aprovação gestor regional", "gr aprovação"], a: "O GR valida o saldo. Se não tiver saldo suficiente, a ocorrência é encaminhada para dupla aprovação do Gestor Nacional + Gestor Financeiro. O GR tem até 7 dias." },
      { q: ["aprovação adm vendas", "administração vendas"], a: "A ADM de Vendas valida as documentações e encaminha para Coordenação de Vendas ou reprova voltando ao representante. Tem até 14 dias após aprovação do GR." },
      { q: ["aprovação coordenação", "coordenação vendas aprovação"], a: "A Coordenação de Vendas faz a última aprovação. Após o OK, aguarda o próximo pedido para encontro de contas. O valor é definitivamente debitado da conta do gestor neste momento." },
      { q: ["o que é encontro de contas", "como funciona encontro de contas"], a: "O encontro de contas é o pagamento da verba descontado no próximo pedido do cliente após a Aprovação da ADM de Vendas. O valor pode ser de até 30% do valor do pedido." },
      { q: ["prazo encontro de contas", "quando encontro de contas"], a: "O encontro de contas ocorre no primeiro pedido após a Aprovação ADM de Vendas. O representante deve sinalizar a implantação do pedido assim que ele for faturado." },
      { q: ["documentos necessários verba", "evidências verba", "o que anexar"], a: "As ocorrências DEVEM ser cadastradas já com as EVIDÊNCIAS e o VALOR FINAL da ação. São necessários: termo de quitação, PAP, comprovação da ação específica e autorizações para valores acima de 50k." },
      { q: ["valor acima 50k", "aprovação jomar", "50 mil"], a: "Ocorrências com VALOR ACIMA DE 50K devem conter APROVAÇÃO DO JOMAR anexada. A responsabilidade de solicitar essa aprovação é do GR/GN." },
      { q: ["verba sem saldo", "sem crédito disponível"], a: "A ocorrência pode ser cadastrada mesmo sem saldo, mas ficará parada na aprovação do GR ou GA. O GR pode encaminhar para dupla aprovação do GN/Auditoria (Adolfo). A aprovação gera crédito como 'VERBA EXTRA GESTÃO'." },
      { q: ["validade saldo", "prazo saldo", "quando saldo expira"], a: "O SALDO DO 1º TRIMESTRE tem validade até 30/04/24. Após essa data, será zerado automaticamente." },
      { q: ["verba suspensa estouro tempo", "estouro de tempo"], a: "Verba com estouro de tempo é aquela que não cumpriu todas as etapas de aprovação dentro do prazo estipulado (30/04). A verba fica suspensa e o saldo é perdido." },
      { q: ["penalidade funcionário", "advertência funcionário", "fluxo punitivo"], a: "Penalidades para funcionários: Parada há 15 dias = Notificação verbal; Parada há 17 dias = Notificação por escrito; Parada há 20 dias = Advertência escrita." },
      { q: ["penalidade cliente auto abatimento", "cliente abatimento indevido"], a: "Penalidades para clientes com auto abatimento indevido: 1ª = Notificação por escrito; 2ª = Retirada do Clube dos Campeões; 3ª = Retirada do PESC; 4ª = Investimentos suspensos por 60 dias." },
      { q: ["cliente com contrato verba", "contrato sell in"], a: "Clientes que possuem contrato NÃO têm direito aos 2% de sell in." },
      { q: ["verba não é desconto", "diferença verba desconto"], a: "Verba NÃO é desconto, NÃO é direito adquirido e PRECISA ter ROI (retorno de investimento) envolvido." },
      { q: ["cliente inadimplente verba", "devendo não recebe verba"], a: "Para pagamento de verba o cliente DEVE estar adimplente com a Embelleze. As verbas não são pagas se o cliente ou qualquer empresa do Grupo estiver com débito no Crédito e Cobrança." },
      { q: ["cliente plano recuperação", "dre negativo verba"], a: "Clientes em plano de recuperação (queda ou DRE negativo): a verba é analisada e possivelmente liberada após aprovação do Gestor Nacional e Presidente, com acompanhamento mínimo de 3 meses." },
      { q: ["liberação automática verba", "dre positivo"], a: "Para liberação automática da verba, o cliente precisa ter DRE positivo." },
      { q: ["terceiros receber verba", "pagar terceiros"], a: "As verbas são pagas SOMENTE ao próprio cliente e NUNCA para terceiros." },
      { q: ["nada consta", "o que é nada consta"], a: "O NADA CONSTA é enviado à Gestão no primeiro dia útil do mês subsequente. Deve conter: assinatura do cliente, CNPJ, representante, gestor de Área e Regional. Se fora dos padrões, será recusado." },
      { q: ["cancelamento devolução nf verba", "nf cancelada verba"], a: "Havendo cancelamento/devolução de NF, o valor da verba SERÁ DEBITADO DO CLIENTE/GESTOR no mês da entrada da devolução/cancelamento." },
      { q: ["ocorrência valor errado", "erro no valor"], a: "Se identificado que o valor cadastrado está errado, a ocorrência será cancelada. Uma nova ocorrência deverá ser cadastrada com o valor correto." },
      { q: ["prazo cadastro ocorrência pesc", "pesc prazo"], a: "Para o PESC: envio dos CNPJs até dia 15 do mês subsequente; apuração pelo Time Trade até 20 dias após; cadastro da ocorrência com evidências até 7 dias após apuração." },
      { q: ["loja estrela prazo", "prazo loja estrela"], a: "Loja Estrela: definição das lojas até dia 30 do último mês do trimestre; coleta de contratos até dia 14; cadastro no Agile até dia 17. Tempo médio para finalização: 60 dias." },
      { q: ["bateu levou", "programa bateu levou"], a: "Bateu/Levou é um programa Trade do 1º TRI. O regional envia o arquivo consolidado com as apurações até dia 15 do mês subsequente." },
      { q: ["feiras eventos trade", "patrocínio evento"], a: "Apenas GRs e GAs podem enviar solicitação para patrocínio de Eventos. E-mail com título: [APORTE TRADE – EVENTO (NOME)]." },
      { q: ["jbp o que é", "joint business plan"], a: "JBPs são planos de negócio Trade. Apenas GRs e GAs podem solicitar. E-mail com título: [APORTE TRADE – JBP CLIENTE (NOME)]." },
      { q: ["evidência rebaixa de preço", "documentos rebaixa"], a: "Para Rebaixa de Preço: relatório com Preço tabela × preço de venda, quantidade, SKU, valor total (documentação carimbada e assinada pelo cliente)." },
      { q: ["evidência inauguração", "documentos inauguração"], a: "Para Inaugurações: até 10% do valor do pedido. Anexar NF, informar código de inauguração e fotos da inauguração." },
      { q: ["evidência treinamento", "documentos treinamento"], a: "Para Treinamentos: anexar NF dos valores gastos e fotos do treinamento/reunião." },
      { q: ["evidência encarte ponto extra", "documentos encarte"], a: "Para Encarte & Ponto Extra: foto do ponto extra com palavra senha (nome da loja + data), foto do encarte físico com data. Online: print com logo da loja." },
      { q: ["evidência convenções feiras", "documentos convenção"], a: "Para Convenções & Feiras: fotos, métricas das negociações e resultado final (sell in + sell out)." },
      { q: ["evidência campanha rca", "documentos campanha"], a: "Para Campanha RCA: métricas, metas, apuração por RCA/supervisor/gerente, realizado total cliente, valores pagos. Comparativo ano anterior × ano atual e evolutivo." },
      { q: ["evidência aniversário cliente", "documentos aniversário"], a: "Para Aniversário do Cliente: inserir as contrapartidas negociadas (métricas, metas, fotos, contratos) e sinalizar os parcelamentos." },
      { q: ["evidência cadastro skus", "documentos novos skus"], a: "Para Cadastro de Novos SKUs: anexar NF." },
      { q: ["pap o que é", "formulário pap"], a: "O PAP deve estar no formulário próprio com assinaturas: Representante Comercial, ADN, Gestor de Área e Gestor Regional. Identificar o cliente com carimbo CNPJ, período e meta de faturamento." },
      { q: ["relatório verba faturamento", "extrato verba gestor"], a: "Será enviado por e-mail um relatório do valor utilizado de verba × faturamento do cliente. A consulta de extrato estará disponível para o trimestre vigente." },
      { q: ["status verba mensal", "acompanhamento verba"], a: "Será enviado mensalmente um status de verba para GN e Diretoria. Após fechamento mensal, os gestores recebem as verbas pendentes no Mercanet." },
      { q: ["ocorrências mensais", "quando cadastrar ocorrência"], a: "As ocorrências do 1º trimestre DEVEM ser cadastradas MENSALMENTE, salvo ações com período maior que um mês." },
      { q: ["email implantação pedido", "aviso implantação"], a: "O e-mail de aviso de implantação deve ter o título: [ENCONTRO DE CONTAS] Nº OCORRÊNCIA MERCANET + Nº PEDIDO." },
      { q: ["verba trade sem saldo", "sem saldo trade"], a: "Não será possível cadastrar VERBA TRADE caso não haja saldo disponível." },
      { q: ["documentação incorreta adm", "adm recusou documentação"], a: "Se a ocorrência chegar na ADM com documentação incorreta, voltará para o representante. Após os acertos, voltará diretamente para aprovação de ADM/Coordenação." },
      { q: ["abatimento duplicata cliente", "cliente não pode abater"], a: "O cliente NÃO possui autorização para abatimentos em duplicatas sem autorização. Se fizer isso, poderá ser PROTESTADO." },
      { q: ["pesc o que é", "programa pesc"], a: "PESC é um programa Trade do 1º TRI. Os CNPJs participantes devem ser enviados para One Drive até o dia 15 do mês subsequente para apuração pelo Time Trade." },
      { q: ["clube dos campeões", "programa campeões"], a: "Clube dos Campeões é um programa Trade para reconhecimento de clientes. Clientes com penalidades podem ser removidos do programa." },
      { q: ["100% auditado", "auditoria verba"], a: "100% das verbas pagas serão AUDITADAS pela Sandra e Adolfo." },
      { q: ["formas pagamento verba", "como verba é paga"], a: "Todos os pagamentos devem ser negociados via ENCONTRO DE CONTAS, limitado a 30% do valor do pedido." },
      { q: ["verba crédito backoffice", "lançamento manual crédito"], a: "O BackOffice faz o lançamento via: Menu > Ações de Verbas > Lançamentos Manuais em Conta Corrente. Selecionar tipo 'Crédito', conta COMERCIAL ou TRADE." },
      { q: ["suspensão ocorrência", "quando ocorrência suspensa"], a: "A ocorrência é suspensa em até 60 dias após cadastro do SALDO, caso as etapas não sejam cumpridas." },
      { q: ["verba não pode sem evidência", "sem evidência não anda"], a: "NÃO será possível dar andamento na solicitação da verba SEM as evidências." },
      { q: ["roi verba", "retorno investimento"], a: "Toda verba precisa ter ROI (retorno de investimento) envolvido. É um investimento que precisa trazer retorno mensurável." },
      { q: ["crédito válido até", "data validade crédito"], a: "O crédito disponível ficará válido até Abr/2024. Após isso, o saldo do 1º trimestre será zerado." },
    ],
  },
  trocas: {
    name: "Agente de Trocas",
    color: "#059669",
    emoji: "🔄",
    subtitle: "Avaria, Vencido, Giro",
    greeting: "Olá! Sou o Agente de Trocas da Embelleze. Posso te ajudar com avarias, vencidos, baixo giro e itens fora de linha. Como posso ajudar?",
    suggested: ["O que é uma avaria?", "Produto vencido tem prazo?", "O que é baixo giro?", "Quem aprova a troca?"],
    qa: [
      { q: ["política de troca", "como funciona troca"], a: "A Política de Trocas Embelleze (Nov/2025) contempla 4 categorias: Avaria, Vencido, Baixo Giro e Fora de Linha. Cada uma tem regras e documentações específicas." },
      { q: ["o que é avaria", "produto avariado"], a: "AVARIA: será considerada APENAS a que ocorrer no ato da entrega. É necessário registrar evidência (foto ou filmagem), nota fiscal de devolução e proceder débito da transportadora." },
      { q: ["avaria no ato entrega", "avaria só na entrega"], a: "Avarias só são aceitas se ocorrerem no ato da entrega. Avarias identificadas posteriormente NÃO são aceitas." },
      { q: ["evidência avaria", "foto avaria", "documentos avaria"], a: "Para Avaria: evidência da ocorrência (foto ou filmagem), nota fiscal de devolução. Válido somente para clientes que apresentarem NF de origem." },
      { q: ["débito transportadora", "avaria transportadora"], a: "Em caso de avaria, deve-se proceder o débito da transportadora responsável pela entrega." },
      { q: ["o que é produto vencido", "item vencido"], a: "ITEM VENCIDO: produto acima do prazo de validade. A Embelleze considera 36 meses para todos os SKUs, com EXCEÇÃO do HENE que são 24 meses." },
      { q: ["prazo validade produtos", "quantos meses validade"], a: "Prazo de validade padrão: 36 meses para todos os SKUs. Exceção: HENE tem validade de 24 meses." },
      { q: ["prazo aceite vencido", "até quando aceita vencido"], a: "Somente são aceitos produtos vencidos com NO MÁXIMO 2 meses após a validade. Produtos vencidos há mais de 2 meses NÃO são aceitos." },
      { q: ["foto palavra chave vencido", "palavra chave mês"], a: "Para vencidos é necessário foto dos itens vencidos com a PALAVRA CHAVE DO MÊS, que muda mensalmente." },
      { q: ["mercadoria devolvida vencida", "documentos devolução vencido"], a: "Se a mercadoria vencida for devolvida: NF de origem da mercadoria + NF de devolução da mercadoria." },
      { q: ["mercadoria descartada vencida", "documentos descarte"], a: "Se a mercadoria vencida for descartada: NF de baixa da mercadoria + documentos do local onde os produtos foram descartados." },
      { q: ["pagamento produto vencido", "como pago vencido"], a: "O pagamento de vencidos é feito via BONIFICAÇÃO pelo preço vigente, com base nos itens obrigatórios e lançamentos do Guia Mix." },
      { q: ["limite por família bonificação", "30% família"], a: "CADA FAMÍLIA BONIFICADA não pode ultrapassar 30% do valor total da bonificação. Regra válida para vencidos, baixo giro e fora de linha." },
      { q: ["quando recebe bonificação", "prazo bonificação"], a: "A BONIFICAÇÃO sempre seguirá com o PRÓXIMO PEDIDO do cliente." },
      { q: ["o que é baixo giro", "item baixo giro"], a: "ITEM DE BAIXO GIRO: item que o cliente deixou de comprar (sell in) e nos 4 meses subsequentes o sell out não foi suficiente para reduzir o estoque." },
      { q: ["documentos baixo giro", "evidências baixo giro"], a: "Para Baixo Giro: foto com palavra chave, documentação de quantidade, print do Cockpit BI das 4 últimas compras, relatório de sell out dos últimos 4 meses e comprovação de estoque acima de 100 dias." },
      { q: ["estoque 100 dias baixo giro", "nível estoque"], a: "Para configurar baixo giro, o estoque do item deve estar ACIMA DE 100 DIAS ao final dos 4 meses sem compra suficiente." },
      { q: ["cockpit bi comprovação", "print cockpit"], a: "Para comprovação de baixo giro/fora de linha: print do BI com as vendas dos últimos 4 meses. Caminho: Cockpit > Marcas > Produto × Sell in (Quantidade)." },
      { q: ["uso dos itens baixo giro", "para que serve bonificação baixo giro"], a: "Os itens de baixo giro devem ser usados para AÇÕES NO PDV: Compre e Ganhe, Estoura Balão, Cesta de Produtos, etc." },
      { q: ["o que é fora de linha", "item fora de linha"], a: "ITEM FORA DE LINHA: item INATIVO para a Embelleze, onde o cliente não realiza mais compras (sell in) e ainda possui estoque elevado. EVITAR chegar nesse estágio!" },
      { q: ["documentos fora de linha", "evidências fora de linha"], a: "Para Fora de Linha: foto com palavra chave, documentação de quantidade, print do Cockpit das últimas 4 compras e estoque do item em dias." },
      { q: ["regras fora de linha", "pagamento fora de linha"], a: "Fora de Linha: bonificação pelo preço vigente, com base nos itens mandatórios do Guia Mix, cada família até 30%, bonificação no próximo pedido, itens para ações no PDV." },
      { q: ["limite cliente bonificação", "% máximo troca"], a: "Limite por cliente: ATÉ 1% do faturamento em 12 meses para PERFUMARIAS; ATÉ 0,3% para DEMAIS CANAIS; ATÉ 0,3% do faturado para a REGIONAL." },
      { q: ["bi bonificações", "monitoramento bonificação"], a: "Monitoramento via BI de Bonificações. Limite máximo por cliente calculado versus faturamento em 12 meses." },
      { q: ["hierarquia aprovação troca", "quem aprova troca"], a: "Hierarquia por valor mensal: ATÉ R$500: ADM Vendas; R$501-R$1.000: ADM Vendas + GR; R$1.001-R$5.000: ADM Vendas + GR + Diretor Comercial; ACIMA R$5.001: ADM Vendas + GR + Sergio Fernandes." },
      { q: ["aprovação até 500", "troca pequena valor"], a: "Para trocas de ATÉ R$500: ADM Vendas verifica notas, imagens e documentação." },
      { q: ["aprovação 501 a 1000"], a: "Para trocas de R$501 a R$1.000: ADM Vendas + Gerente Regional." },
      { q: ["aprovação 1001 a 5000"], a: "Para trocas de R$1.001 a R$5.000: ADM Vendas + Gerente Regional + Diretor Comercial." },
      { q: ["aprovação acima 5001", "aprovação sergio fernandes"], a: "Para trocas ACIMA de R$5.001: ADM Vendas + Gerente Regional + Sergio Fernandes (aprovação máxima)." },
      { q: ["processo aprovação interno", "aprovação interna troca"], a: "Os processos de troca acontecem MEDIANTE AVALIAÇÃO E APROVAÇÃO INTERNA. Não é automático." },
      { q: ["nf origem troca", "nota fiscal origem"], a: "Para a maioria dos processos de troca é necessário apresentar a NF de origem da mercadoria." },
      { q: ["sell out baixo giro", "relatório sell out"], a: "Para Baixo Giro é necessário o relatório de SELL OUT do cliente dos últimos 4 meses para comprovar que o estoque não foi reduzido." },
      { q: ["sell in comprovação", "comprovação compras"], a: "A comprovação do sell in é feita via print do COCKPIT BI: Cockpit > Marcas > Produto × Sell in (Quantidade)." },
      { q: ["guia mix bonificação", "itens obrigatórios bonificação"], a: "A bonificação é feita com base nos ITENS OBRIGATÓRIOS (mandatórios) e LANÇAMENTOS do GUIA MIX." },
      { q: ["hene prazo validade", "validade hene diferente"], a: "O HENE tem prazo de validade de 24 MESES, diferente dos demais SKUs que têm 36 meses." },
      { q: ["foto palavra chave", "o que é palavra chave"], a: "A palavra chave é um código mensal que deve aparecer nas fotos dos produtos para comprovar que a foto foi tirada no mês da solicitação, evitando fraudes." },
      { q: ["prazo validade troca", "quando posso fazer troca"], a: "Avarias: apenas no ato da entrega. Vencidos: até 2 meses após a validade. Baixo giro: após 4 meses sem sell out suficiente. Fora de linha: item inativo da Embelleze." },
      { q: ["troca não aceita", "quando troca não é aceita"], a: "Trocas não aceitas: avaria não no ato da entrega; vencido há mais de 2 meses; cliente sem NF de origem; documentação incompleta; limite percentual de faturamento atingido." },
      { q: ["bonificação preço vigente", "qual preço bonificação"], a: "A bonificação é calculada pelo PREÇO VIGENTE dos produtos no momento da solicitação." },
      { q: ["ações pdv bonificação", "como usar bonificação"], a: "Produtos de bonificação (baixo giro e fora de linha) devem ser usados em ações no PDV: Compre e Ganhe, Estoura Balão, Cesta de Produtos." },
      { q: ["documentação cliente comprovação", "como comprovar quantidade"], a: "A documentação do cliente para comprovação de quantidade inclui inventário, relatórios de estoque ou documentação oficial do cliente." },
      { q: ["política vigente troca", "versão política troca"], a: "A Política de Trocas vigente é de NOV/2025, administrada pelo Adm.Vendas_Março26." },
      { q: ["devolução mercadoria vencida", "retorno mercadoria"], a: "Para mercadoria vencida, será verificada a possibilidade de descarte ou retorno à Embelleze. A decisão é avaliada internamente." },
      { q: ["nf baixa descarte", "nota fiscal descarte"], a: "Para mercadoria vencida descartada: NF de baixa da mercadoria + documentos do local de descarte (cooperativa, aterro credenciado)." },
      { q: ["quanto tempo baixo giro", "4 meses baixo giro"], a: "O período de análise para Baixo Giro é de 4 MESES. O cliente deve ter parado de comprar e nos 4 meses seguintes o sell out não ter sido suficiente para reduzir o estoque abaixo de 100 dias." },
      { q: ["como iniciar processo troca", "passo a passo troca"], a: "Passo a passo: 1) Identifique o tipo (avaria, vencido, baixo giro, fora de linha); 2) Reúna a documentação exigida; 3) Fotos com palavra chave do mês; 4) Submeta para aprovação conforme hierarquia de valores; 5) Aguarde avaliação interna." },
      { q: ["quem solicita troca", "como cliente solicita"], a: "O processo de troca é iniciado pelo Representante Comercial junto ao cliente. O representante coleta a documentação e submete para a hierarquia de aprovação." },
      { q: ["troca perfumaria limite", "limite perfumaria bonificação"], a: "Para Perfumarias, o limite máximo de bonificação é de ATÉ 1% do faturamento em 12 meses." },
      { q: ["troca outros canais limite", "demais canais bonificação"], a: "Para Demais Canais (não perfumarias), o limite máximo é de ATÉ 0,3% do faturamento em 12 meses." },
      { q: ["regional limite bonificação", "limite regional troca"], a: "A Regional tem limite de ATÉ 0,3% do faturado para bonificações/trocas." },
      { q: ["check adm vendas", "o que adm verifica"], a: "A ADM de Vendas verifica em todas as faixas: notas fiscais, imagens (fotos com palavra chave) e toda documentação exigida por tipo de troca." },
      { q: ["sergio fernandes quem é", "diretor comercial troca"], a: "Sergio Fernandes é o Diretor Comercial e aprovador máximo para trocas acima de R$5.001." },
      { q: ["estoque elevado fora linha", "estoque alto fora linha"], a: "Para Fora de Linha, o cliente deve possuir estoque ELEVADO do item. O nível de estoque em dias deve ser comprovado como documentação." },
      { q: ["representante aprovação troca", "rep aprova troca"], a: "O Representante inicia o processo de troca, coleta a documentação e submete para a hierarquia de aprovação conforme o valor." },
      { q: ["4 meses sem compra", "período análise giro"], a: "O período de 4 meses é específico para análise de BAIXO GIRO. Para fora de linha, o item simplesmente deve estar inativo na Embelleze." },
      { q: ["reclassificar troca", "mudar tipo troca"], a: "Se o tipo de troca foi registrado errado, a ocorrência deve ser cancelada e uma nova aberta corretamente. Acione a ADM de Vendas." },
      { q: ["desconto ao invés troca", "troca vs desconto"], a: "A Embelleze não faz desconto em substituição à troca. A compensação aprovada é sempre via BONIFICAÇÃO (produtos), nunca em dinheiro." },
    ],
  },
  devolucao: {
    name: "Agente de Devolução",
    color: "#DC2626",
    emoji: "↩️",
    subtitle: "Retorno de Mercadorias",
    greeting: "Olá! Sou o Agente de Devolução da Embelleze. Posso te ajudar sobre processos de devolução de mercadorias. Como posso ajudar?",
    suggested: ["Como solicitar devolução?", "Preciso de NF para devolver?", "Quanto tempo tenho?", "A devolução impacta minha verba?"],
    qa: [
      { q: ["o que é devolução", "como funciona devolução"], a: "Devolução é o retorno de mercadoria à Embelleze. Pode ocorrer por: avaria no ato da entrega, produto vencido, item fora de linha, ou outras situações previstas na política." },
      { q: ["devolução avaria", "devolver produto avariado"], a: "Devolução por avaria: só aceita no ato da entrega. Necessário: evidência (foto/filmagem), NF de devolução e débito na transportadora. Válido apenas para clientes com NF de origem." },
      { q: ["nf de devolução", "nota fiscal devolução"], a: "A Nota Fiscal de Devolução é documento obrigatório. Deve ser emitida pelo cliente devolvendo a mercadoria para a Embelleze." },
      { q: ["devolução vencido retorno", "devolver produto vencido"], a: "Para devolução de produto vencido por retorno físico: NF de origem da mercadoria + NF de devolução." },
      { q: ["descarte produto vencido", "não devolve descarta"], a: "Em vez de devolver, o produto vencido pode ser descartado. Necessário: NF de baixa + documentos do local de descarte." },
      { q: ["devolução impacto verba", "verba e devolução"], a: "Havendo CANCELAMENTO/DEVOLUÇÃO de NF, o valor da VERBA SERÁ DEBITADO DO CLIENTE/GESTOR no mês da entrada. Devoluções impactam diretamente as verbas!" },
      { q: ["prazo aceite devolução", "quando pode devolver"], a: "Avaria: apenas no ato da entrega. Vencido: produto com no máximo 2 meses além do prazo de validade. Outros casos: mediante avaliação interna." },
      { q: ["transportadora devolução", "frete devolução"], a: "Em caso de avaria na entrega, deve-se proceder o DÉBITO DA TRANSPORTADORA. O custo da avaria recai sobre a transportadora." },
      { q: ["devolução sem nf origem", "cliente sem nota fiscal"], a: "O processo de devolução é válido SOMENTE para clientes que apresentarem NF de origem." },
      { q: ["como solicitar devolução", "processo devolução passo a passo"], a: "Para solicitar: 1) Identifique o motivo; 2) Reúna a NF de origem; 3) Faça fotos com palavra chave; 4) Emita a NF de devolução; 5) Submeta para aprovação conforme hierarquia de valores." },
      { q: ["devolução bonificação", "devolveu recebe bonificação"], a: "Para vencidos devolvidos, a compensação é feita via BONIFICAÇÃO pelo preço vigente, com base nos itens obrigatórios do Guia Mix. Segue com o próximo pedido." },
      { q: ["o que é nf de baixa", "nota fiscal de baixa"], a: "A NF de Baixa é emitida quando o produto é descartado (não devolvido fisicamente). Comprova que o produto foi dado baixa no estoque do cliente." },
      { q: ["documentos descarte credenciado", "local descarte"], a: "Para mercadoria descartada, além da NF de baixa, são necessários documentos do local onde os produtos foram descartados (cooperativa, aterro credenciado, etc.)." },
      { q: ["devolução fora de linha", "devolver item inativo"], a: "Itens fora de linha: necessário foto com palavra chave, documentação de quantidade, comprovação das 4 últimas compras (print Cockpit) e estoque em dias." },
      { q: ["devolução impacta gestor", "gestor perde saldo devolução"], a: "Sim, havendo cancelamento ou devolução de NF, o valor da verba associada é DEBITADO do CLIENTE/GESTOR no mês da entrada." },
      { q: ["quem aprova devolução", "hierarquia devolução"], a: "Hierarquia por valor: ATÉ R$500: ADM Vendas; R$501-R$1.000: ADM Vendas + GR; R$1.001-R$5.000: ADM Vendas + GR + Diretor Comercial; ACIMA R$5.001: ADM Vendas + GR + Sergio Fernandes." },
      { q: ["vencido 36 meses", "prazo validade devolução"], a: "Prazo de validade: 36 meses (padrão) e 24 meses para HENE. Após o vencimento, há até 2 meses de prazo para solicitação." },
      { q: ["evidência devolução foto", "foto devolução"], a: "Para devolução de vencidos e outros tipos: foto dos itens com a PALAVRA CHAVE DO MÊS é obrigatória." },
      { q: ["devolução mercadoria transporte", "produto danificado transporte"], a: "Danos durante o transporte são de responsabilidade da transportadora. O cliente deve registrar no ato da entrega, tirar fotos, emitir NF de devolução e acionar o débito da transportadora." },
      { q: ["bonificação 30% família", "limite família devolução"], a: "Em qualquer tipo de troca/devolução compensada por bonificação, CADA FAMÍLIA não pode ultrapassar 30% do valor total da bonificação." },
      { q: ["processo avaliação interna", "devolução avaliação"], a: "O processo acontece MEDIANTE AVALIAÇÃO E APROVAÇÃO INTERNA da Embelleze. Não é automático — cada caso é analisado." },
      { q: ["rastreio devolução", "acompanhar devolução"], a: "Acompanhe o status com o Representante Comercial ou ADM de Vendas responsável pela sua conta." },
      { q: ["devolução por qualidade", "produto com defeito"], a: "Para defeito identificado na entrega: siga o processo de avaria. Para defeito posterior: entre em contato com o Representante para avaliação caso a caso." },
      { q: ["prazo devolução após entrega", "tempo para devolver"], a: "Avarias: deve ser no ato da entrega. Vencidos: dentro de 2 meses após o vencimento. Outros casos são analisados individualmente." },
      { q: ["devolução impacta sell in", "devolução metas"], a: "Devoluções podem impactar os indicadores de sell in do cliente e da regional. Cancelamentos de NF debitam as verbas vinculadas." },
      { q: ["devolução cliente perfumaria", "perfumaria devolução"], a: "Perfumarias têm limite de bonificação de até 1% do faturamento em 12 meses para compensação de trocas/devoluções." },
      { q: ["rejeitar devolução", "devolução negada"], a: "A devolução pode ser negada quando: avaria não é no ato da entrega; vencido há mais de 2 meses; documentação incompleta; sem NF de origem; limite percentual atingido." },
      { q: ["devolução e protesto", "abatimento indevido cliente"], a: "Se o cliente fizer abatimento/devolução indevidamente sem autorização, poderá ser PROTESTADO. Todo processo deve seguir o fluxo formal." },
      { q: ["devolução cria crédito", "crédito por devolução"], a: "A compensação por devolução aprovada é feita via BONIFICAÇÃO (crédito em produtos), não em dinheiro." },
      { q: ["prazo receber bonificação devolução", "quando recebe bonificação"], a: "A bonificação compensatória sempre seguirá com o PRÓXIMO PEDIDO do cliente após aprovação completa." },
      { q: ["foto filmagem avaria", "como registrar avaria"], a: "Para avaria: tire fotos ou grave um vídeo no momento da entrega, mostrando claramente o dano. Esse registro é a EVIDÊNCIA obrigatória." },
      { q: ["produto sem validade visível", "sem data validade"], a: "Se o produto não tiver a data de validade visível, documente isso nas fotos e reporte ao Representante. A situação será avaliada caso a caso." },
      { q: ["estoque dias fora linha", "como calcular estoque dias"], a: "O estoque em dias é calculado dividindo a quantidade em estoque pela média de saída (sell out) diária. Comprova que o estoque está elevado." },
      { q: ["baixo giro deve parar compra", "parar compra baixo giro"], a: "Sim, para configurar como baixo giro, o cliente deve ter PARADO de comprar o item (sell in zerado) e nos 4 meses seguintes o sell out não ter reduzido o estoque abaixo de 100 dias." },
      { q: ["limite devolução atingido", "excedeu limite bonificação"], a: "Se o cliente atingiu o limite de bonificação, novas solicitações de troca/devolução não podem ser compensadas via bonificação no período." },
      { q: ["impacto devolução meta regional", "regional meta devolução"], a: "A regional tem limite de 0,3% do faturado para bonificações. Devoluções excessivas impactam esse limite." },
      { q: ["cockpit fora linha", "como verificar fora linha cockpit"], a: "Para comprovar fora de linha: acesse Cockpit > Marcas > Produto × Sell in (Quantidade). Print mostrando as compras zeradas." },
      { q: ["devolução registrada errado", "erro no processo devolução"], a: "Se houve erro no registro, acione a ADM de Vendas imediatamente. A ocorrência pode precisar ser cancelada e recadastrada corretamente." },
      { q: ["devolução sem aprovação", "devolução não autorizada"], a: "Devolução sem aprovação prévia não é aceita. Todo processo deve seguir o fluxo formal. Devoluções não autorizadas podem levar ao protesto do cliente." },
      { q: ["devolução meses anteriores", "retroativo devolução"], a: "As devoluções têm prazo específico por tipo. Avaria: apenas no ato da entrega. Vencido: até 2 meses após validade. Processos retroativos além desses prazos não são aceitos." },
      { q: ["responsável processo devolução", "quem cuida devolução"], a: "O processo de devolução é gerenciado pelo Representante Comercial junto ao cliente, com aprovação da ADM de Vendas e hierarquia conforme o valor." },
      { q: ["desconto ao invés devolução", "devolução vs desconto"], a: "A Embelleze não faz desconto em substituição à devolução. A compensação é sempre via BONIFICAÇÃO (produtos), nunca em dinheiro." },
      { q: ["comunicar devolução urgente", "devolução urgente avaria"], a: "Para avaria: urgência máxima — deve ser registrada NO ATO DA ENTREGA. Não deixe para depois. Acione imediatamente o Representante e registre tudo com foto/vídeo." },
      { q: ["devolução com pedido novo", "pedido e devolução juntos"], a: "A bonificação compensatória sempre acompanha o PRÓXIMO PEDIDO do cliente. O pedido precisa estar ativo e aprovado." },
      { q: ["cliente sem pedido devolução", "sem pedido recebe bonificação"], a: "A bonificação aguarda o próximo pedido. Se o cliente não fizer pedido, a bonificação ficará pendente." },
      { q: ["aprovação devolução prazo", "quanto tempo aprova devolução"], a: "O prazo de aprovação segue a hierarquia: ADM Vendas verifica documentação, Gerente Regional (conforme valor), Diretor Comercial (conforme valor)." },
      { q: ["ações pdv com devolução", "usar bonificação pdv"], a: "Os produtos recebidos via bonificação (baixo giro e fora de linha) DEVEM ser usados em ações no PDV. Não podem ser simplesmente revendidos." },
      { q: ["devolução terceiros", "receber devolução nome terceiro"], a: "As compensações (bonificações) por devolução são pagas SOMENTE ao próprio cliente, nunca para terceiros." },
      { q: ["devolução produto correto", "devolver produto errado entregue"], a: "Se recebeu produto diferente do pedido, acione o Representante imediatamente para resolver com a área de logística." },
      { q: ["reclassificar devolução", "mudar tipo devolução"], a: "Se o tipo de devolução foi registrado errado, a ocorrência deve ser cancelada e uma nova aberta corretamente. Acione a ADM de Vendas." },
      { q: ["impacto sell in devolução", "devolução afeta metas"], a: "Devoluções e cancelamentos de NF impactam negativamente o sell in e podem reduzir o saldo de verbas do gestor. Gerencie bem os estoques para evitar devoluções desnecessárias." },
      { q: ["devolução política canais", "canal devolução diferente"], a: "A política cobre todos os canais (varejistas, atacados, perfumarias), com limites diferentes: 1% perfumarias e 0,3% demais canais." },
      { q: ["endereço devolução", "onde enviar devolução"], a: "O endereço e logística para devolução física são combinados com o Representante Comercial e equipe de Logística. O processo é acordado caso a caso após aprovação." },
      { q: ["produto por marca devolução", "qual marca pode devolver"], a: "A política cobre todos os produtos Embelleze (Maxton, Novex, Natucor, etc.). O Guia Mix determina como a bonificação compensatória é distribuída por marca." },
    ],
  },
  prorrogacao: {
    name: "Agente de Prorrogação",
    color: "#D97706",
    emoji: "📅",
    subtitle: "Prazos & Vencimentos",
    greeting: "Olá! Sou o Agente de Prorrogação da Embelleze. Posso te ajudar sobre prorrogação de prazos, vencimentos e condições especiais. Como posso ajudar?",
    suggested: ["Como solicitar prorrogação?", "O prazo de verba pode ser prorrogado?", "O que acontece se o prazo vencer?", "Quando o crédito do 1º TRI expira?"],
    qa: [
      { q: ["o que é prorrogação", "definição prorrogação"], a: "Prorrogação é a extensão do prazo de pagamento ou vencimento de títulos/duplicatas do cliente com a Embelleze. Exige aprovação formal e NÃO é concedida automaticamente." },
      { q: ["como solicitar prorrogação", "pedir prorrogação"], a: "A solicitação deve ser feita formalmente pelo Representante Comercial junto ao GA e GR, com justificativa, prazo solicitado e plano de regularização." },
      { q: ["quem aprova prorrogação", "hierarquia prorrogação"], a: "Prorrogações são aprovadas pelo Crédito e Cobrança da Embelleze, com envolvimento do GR e, conforme o valor/prazo, do Gestor Nacional." },
      { q: ["cliente inadimplente verba prorrogação", "inadimplente prorrogação"], a: "Cliente com débito no Crédito e Cobrança não recebe verba. Para solicitar prorrogação, o cliente precisa estar com seu histórico em análise." },
      { q: ["prazo prorrogação", "quanto tempo prorrogação"], a: "O prazo de prorrogação é definido caso a caso pelo Crédito e Cobrança. Depende do perfil do cliente e da justificativa apresentada." },
      { q: ["prorrogação automática", "automático prazo"], a: "NÃO existe prorrogação automática. O cliente NÃO pode fazer abatimentos ou prorrogações por conta própria. Se fizer isso, poderá ser PROTESTADO." },
      { q: ["protesto cliente", "quando cliente é protestado"], a: "O cliente pode ser protestado se fizer abatimentos em duplicatas sem autorização, prorrogações unilaterais ou qualquer ação financeira não acordada com a Embelleze." },
      { q: ["prorrogação verba impacto", "prazo verba prorrogação"], a: "O prazo de validade das verbas (1º TRI expira 30/04/24) NÃO é prorrogável. Verbas com estouro de tempo são suspensas independente de qualquer negociação." },
      { q: ["saldo do trimestre expirou", "crédito zerado trimestre"], a: "O saldo do 1º Trimestre expira em 30/04/24. Após essa data, é zerado automaticamente. Não há prorrogação de saldo entre trimestres." },
      { q: ["encontro de contas prorrogação", "adiar encontro de contas"], a: "O encontro de contas ocorre no primeiro pedido após aprovação da ADM de Vendas. Não é possível adiar indefinidamente." },
      { q: ["cliente plano recuperação prazo", "recuperação prazo especial"], a: "Clientes em plano de recuperação (DRE negativo) têm verbas analisadas com acompanhamento mínimo de 3 meses. É uma condição especial, não uma prorrogação de pagamento." },
      { q: ["negociação prazo duplicata", "renegociar duplicata"], a: "Renegociações de duplicatas e prazos são tratadas exclusivamente pelo Crédito e Cobrança da Embelleze. O Representante pode intermediar, mas a decisão é do financeiro." },
      { q: ["prorrogação dre negativo", "empresa com prejuízo prazo"], a: "Empresas com DRE negativo não têm liberação automática de verbas. Para receber verbas, precisam ter DRE positivo ou aprovação especial do Gestor Nacional e Presidente." },
      { q: ["verba expirada pode reativar", "verba vencida reativar"], a: "Verbas suspensas por estouro de tempo (após 30/04) são zeradas e NÃO podem ser reativadas. É fundamental cumprir os prazos dentro do trimestre vigente." },
      { q: ["prazo validade crédito verba", "quanto tempo tenho para usar verba"], a: "O crédito de verba fica válido até Abr/2024 (1º trimestre de 2024). O prazo máximo de cadastro de ocorrência é até 15/04/24." },
      { q: ["suspensão ocorrência 60 dias", "60 dias ocorrência"], a: "A ocorrência é suspensa em até 60 dias após cadastro do SALDO, caso as etapas não sejam cumpridas. Esse prazo NÃO é prorrogável." },
      { q: ["prorrogação loja estrela", "prazo loja estrela prorrogar"], a: "O processo de Loja Estrela tem tempo médio de 60 dias. Os prazos internos são definidos e devem ser cumpridos conforme o cronograma." },
      { q: ["atraso aprovação fluxo", "gestor atrasou aprovação"], a: "Cada aprovador tem prazo máximo de 7-14 dias por etapa. Se não cumprir, a ocorrência pode estourar o tempo. É responsabilidade de cada parte cumprir seu prazo." },
      { q: ["prazo representante lançar", "atraso representante cadastro"], a: "O representante tem responsabilidade de cadastrar as ocorrências até o dia 15 do mês subsequente. O prazo máximo geral é até 15/04/24 para o 1º TRI." },
      { q: ["prorrogação pesc prazo", "pesc prazo especial"], a: "Para o PESC, o prazo para envio dos CNPJs é até dia 15 do mês subsequente e a apuração leva até 20 dias. Esses prazos são FIXOS." },
      { q: ["validade bonificação", "prazo bonificação vence"], a: "A bonificação de trocas acompanha o próximo pedido do cliente. Se o cliente ficar sem fazer pedido, a bonificação fica pendente." },
      { q: ["prorrogação inauguração prazo", "inauguração prazo verba"], a: "Para inaugurações, o prazo de cadastro segue as regras gerais: até 30 dias após a ação ou até 15/04 para o 1º TRI." },
      { q: ["quando cliente pode pedir prazo", "condição especial prazo"], a: "O cliente pode solicitar condições especiais de prazo através do Representante Comercial, que levará ao GR e ao Crédito e Cobrança. Cada caso é analisado individualmente." },
      { q: ["verba parcelamento", "pagar verba em parcelas"], a: "Verbas de aniversário de cliente podem ter parcelamento — devem ser sinalizados no cadastro da ocorrência. O parcelamento de outros tipos depende de negociação específica." },
      { q: ["prazo vencimento ocorrência comercial", "quando comercial expira"], a: "Ocorrências comerciais do 1º trimestre devem ser registradas mensalmente e finalizadas até 30/04/24." },
      { q: ["atraso aprovação ga gr", "ga gr atrasaram"], a: "Se GA ou GR atrasarem a aprovação (além de 10 dias), a ocorrência entra em risco de estouro de tempo. O representante deve cobrar ativamente as aprovações." },
      { q: ["prazo negociação jbp", "jbp prazo"], a: "JBPs têm prazo de aprovação e operacionalização definidos pelo Time Trade. Contate o Trade diretamente para prazos específicos." },
      { q: ["verba trimestre seguinte", "saldo carryover"], a: "NÃO há transferência de saldo entre trimestres. O saldo não utilizado do 1º TRI é zerado em 30/04. Um novo saldo é disponibilizado para o 2º TRI." },
      { q: ["prazo máximo resolução processo", "quanto tempo resolve"], a: "Verbas comerciais: até 30/04/24 (1º TRI). Trocas/bonificações: até aprovação e próximo pedido. Loja Estrela: ~60 dias. PESC: ~20 dias de apuração + 7 dias de cadastro." },
      { q: ["urgência prazo vence amanhã", "prazo urgente"], a: "Se o prazo está vencendo: acione IMEDIATAMENTE o Representante Comercial e GA. Escale para GR se necessário. Prazo vencido = perda da verba. Não espere!" },
      { q: ["prazo adm vendas 14 dias", "adm 14 dias"], a: "A ADM de Vendas tem até 14 dias após aprovação do GR (verbas comerciais) ou 7 dias após aprovação do Trade (Trade/Loja Estrela) para finalizar." },
      { q: ["prorrogação por força maior", "evento imprevisto prazo"], a: "Situações de força maior podem ser levadas ao GR/GN para avaliação especial. Não há garantia de prorrogação — cada caso é analisado com justificativa formal." },
      { q: ["prazo feiras eventos", "evento prazo aprovação"], a: "Feiras & Eventos: solicitação deve ser feita de forma antecipada e alinhada com o Trade. Não há prazo padrão — depende do evento e da antecedência." },
      { q: ["data ação retroativa", "lançar ação passada"], a: "O campo 'Data de Ação' no Mercanet permite selecionar somente 1 mês anterior à data de lançamento. Ações mais antigas não podem ser lançadas retroativamente." },
      { q: ["suspensão verba 60 dias etapas", "o que acontece após 60 dias"], a: "Após 60 dias do cadastro do saldo sem etapas cumpridas, a ocorrência é SUSPENSA automaticamente. O valor é perdido para aquela ação específica." },
      { q: ["prazo vigência crédito trade", "trade crédito vence quando"], a: "Os créditos de verbas Trade são disponibilizados de acordo com os programas do trimestre. A vigência específica é comunicada pelo Time Trade para cada programa." },
      { q: ["prazo ação aniversário", "aniversário prazo registro"], a: "Ações de Aniversário devem ser cadastradas conforme o prazo geral: até 30 dias após a ação, ou até 15/04 para o 1º TRI." },
      { q: ["ga gr prazo aprovação 10 dias", "10 dias aprovação gestor"], a: "GA e GR têm até 10 dias após o cadastro da Ação para aprovar (verbas comerciais). Para PESC e Trade, o prazo é de 7 dias após o representante cadastrar a ocorrência." },
      { q: ["prazo coordenação vendas", "coord vendas prazo"], a: "A Coordenação de Vendas tem até 14 dias após aprovação do GR (verbas comerciais) ou 7 dias após aprovação do ADM (Trade/Loja Estrela)." },
      { q: ["prorrogação aprovação gestor nacional", "gn prazo aprovação extra"], a: "Quando a ocorrência vai para dupla aprovação GN/Auditoria (por falta de saldo), o prazo é de até 10 dias após o cadastro. Com aprovação, o crédito é gerado e o fluxo segue." },
      { q: ["crédito semanal verba", "quando crédito disponível"], a: "Os créditos de verbas comerciais são disponibilizados toda sexta-feira." },
      { q: ["encontro de contas 30%", "limite encontro de contas"], a: "O valor do encontro de contas é limitado a ATÉ 30% do valor do pedido. Verbas maiores podem ser divididas em múltiplos pedidos." },
      { q: ["prazo validade ação pesc mensal", "pesc vigência mensal"], a: "O PESC é um programa mensal. Os CNPJs de cada mês devem ser enviados até o dia 15 do mês subsequente." },
      { q: ["prorrogação aprovação jomar", "prazo jomar 50k"], a: "Para verbas acima de 50k com aprovação do JOMAR, o prazo também segue o fluxo de 10 dias por etapa. O GR/GN é responsável por solicitar dentro do prazo." },
      { q: ["prazo loja estrela mensal", "loja estrela ciclo mensal"], a: "Loja Estrela: coleta de informações entre dias 20-30 de cada mês, apuração entre dias 5-10 do mês subsequente, crédito até dia 30 do mês subsequente." },
      { q: ["prazo bateu levou", "bateu levou mensal"], a: "Bateu/Levou: ciclo mensal similar ao PESC. O regional envia o arquivo consolidado até dia 15 do mês subsequente." },
      { q: ["quando usar prazo emergência", "emergência prazo escalonamento"], a: "Em urgência com prazo vencendo: 1) Acione o Representante; 2) Representante escala para GA; 3) GA escala para GR; 4) GR pode acionar GN. Aja rápido!" },
      { q: ["prorrogação não existe automático", "prazo não é automático"], a: "NA EMBELLEZE, NÃO EXISTE prorrogação automática de nenhum prazo. Todo prazo que vence sem ação é definitivamente encerrado. Gestão ativa dos prazos é obrigatória." },
      { q: ["pagamento fora prazo cliente", "cliente pagou atrasado"], a: "Se o cliente pagou atrasado mas está em dia, a situação é avaliada pelo Crédito e Cobrança. Histórico de atraso pode impactar a aprovação de condições especiais." },
      { q: ["renegociação prazo pedido", "prazo pedido atrasado"], a: "Renegociações de prazo de pedido/fatura devem ser tratadas com o Crédito e Cobrança da Embelleze através do Representante Comercial ou GR." },
      { q: ["prazo encontro contas venceu", "encontro de contas atrasou"], a: "O encontro de contas ocorre no PRIMEIRO PEDIDO após aprovação ADM. Se o pedido não for faturado, aguarda. Mas a verba pode ser suspensa após 60 dias do saldo." },
      { q: ["prazo ação data lançamento", "retroativo mercanet"], a: "O campo 'Data de Ação' no Mercanet permite seleção de somente 1 mês anterior. Ações mais antigas não podem ser cadastradas retroativamente no sistema." },
      { q: ["quando alertar prazo", "como monitorar prazos"], a: "Monitore semanalmente as ocorrências em aberto no MERCANET. Acompanhe as aprovações pendentes por GA e GR. Controle o calendário de prazos do trimestre ativamente." },
    ],
  },
};

export function findAnswer(agentKey, question) {
  const agent = KNOWLEDGE[agentKey];
  if (!agent) return null;
  const q = question
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");
  let bestMatch = null;
  let bestScore = 0;
  for (const entry of agent.qa) {
    for (const keyword of entry.q) {
      const kw = keyword.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
      const words = kw.split(" ").filter((w) => w.length > 3);
      let score = 0;
      if (q.includes(kw)) score = 100;
      else { for (const w of words) { if (q.includes(w)) score += 20; } }
      if (score > bestScore) { bestScore = score; bestMatch = entry.a; }
    }
  }
  return bestScore >= 20 ? bestMatch : null;
}
